### ISSUE TITLE
Pip & Conda and release assets

### ISSUE THREAD

**Issue by mmann1123** [jgrss/geowombat#123]
I think the major hurdle for most people (nubes like me at least) have with geowombat is the complexity of the install (outside linux).  Someone already got a semi-working [conda feedstock for v 1.2](https://github.com/conda-forge/geowombat-feedstock/blob/main/recipe/meta.yaml) up. But it points to .tar.gz release assets like this example from rasterio [https://github.com/rasterio/rasterio/releases](https://github.com/rasterio/rasterio/releases). 

Maybe its because I am not the owner of the repository, but I'm not seeing the "create a release" button for geowombat on github [for example](https://www.toolsqa.com/git/github-releases/). I am assuming this is something we can automate through circleci, but not sure.  

Just wondering if that's in the works. Or if you can do it manually. I would love to get the conda feedstock running across all the systems.

**Comment by jgrss** [comment]
Completely agree with getting packaged releases. I am close to automating this with CircleCI (see [this step](https://github.com/jgrss/geowombat/blob/b81a9b410405a3b1bcdb02d09650c1f111f85822/.circleci/config.yml#L101)).

**Comment by jgrss** [comment]
The GitHub auto-release is now working: https://app.circleci.com/pipelines/github/jgrss/geowombat/146/workflows/56cd2cb0-d3f4-41fa-99f0-356ee91cded8/jobs/199.

**Comment by mmann1123** [comment]
Looks like [conda smitty](https://conda-forge.org/docs/user/ci-skeleton.html) can help with CI.  I'll start with the basics on the existing feedstock but maybe we move to this.

**Comment by mmann1123** [comment]
Ok I have tried a bunch of things mostly to no avail. The following builds locally (need to switch type back to .yaml) for linux. But I haven't been able to[ get it to build on osx or windows](https://conda-forge.org/docs/maintainer/adding_pkgs.html#running-tests-locally-for-staged-recipes). 

[meta working_on_linux.txt](https://github.com/jgrss/geowombat/files/8875255/meta.working_on_linux.txt)
@jgrss

**Comment by mmann1123** [comment]
I also ran into this on building a pypi package with circle ci
[https://www.guyrking.com/2019/12/28/create-a-pypi-package-using-circleci-and-github.html](https://www.guyrking.com/2019/12/28/create-a-pypi-package-using-circleci-and-github.html)

**Comment by jgrss** [comment]
Here's an update on getting an official Dockerfile for the project. See [this branch](https://github.com/jgrss/geowombat/blob/jgrss/docker/dockerfiles/README.md). Let me know if you can successfully create the Docker image.

**Comment by mmann1123** [comment]
@jgrss I noticed the conda feedstock PR that are getting generated. I don't really understand how its getting generated, maybe on circleci side, but all the pipelines are failing with:

ModuleNotFoundError: No module named 'retry'

Looks like a simple fix.

**Comment by jgrss** [comment]
Hey @mmann1123 what action do I need to take here? I am unfamiliar with conda feedstocks.

**Comment by mmann1123** [comment]
Is circleci generating the scripts and pull requests? If so that's amazing

I will look into how to trigger the merge

@jgrss

**Comment by mmann1123** [comment]
@jgrss Ok looks like its not the easy win I was hoping for.  So I am assuming circle CI has been generating these changes but all three OS builds are failing because retry is missing.  
`ModuleNotFoundError: No module named 'retry'`

Because I don't want to 'f with anything on the circle ci side, I will leave it to you to add retry. But for now I will pull the conda-forge fork add retry and push it again. See if that fixes it.

**Comment by mmann1123** [comment]
Ok I pulled some ideas from rasterio's feedstock and made some progress! Seems like its building properly on all OS except linux python 3.7 

Can you @jgrss take a look at this and see if you have any ideas? 


https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=524817&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e

**Comment by mmann1123** [comment]
Got it! I think they will merge after review.
[see PR](https://github.com/conda-forge/geowombat-feedstock/pull/16/files)

**Comment by jgrss** [comment]
Looks good to me--nice work. So will this get triggered on every PR merge?

**Comment by mmann1123** [comment]
**Yes please**

![Screenshot from 2022-06-24 16-59-20](https://user-images.githubusercontent.com/5185364/175666691-daae340e-ff6b-46df-b2ea-0901a672674b.png)
