### ISSUE TITLE
Unable to install on Windows with conda

### ISSUE THREAD

**Issue by cefect** [jgrss/geowombat#182]
Installing on Windows 10, I followed the [Easiest Install](https://geowombat.readthedocs.io/en/latest/install.html#easiest-install) instructions using conda. This led to repeated 'Solving environment: failed...'.

Then I tried the [Detailed Install](https://geowombat.readthedocs.io/en/latest/install.html#detailed-install) further down on the same page, which is slightly different and seems redundant. 

As this doesn't actually include a command to install geowombat at the end, I tried doing this with conda (per the 'Easiest') with the same result.

In the same environment, I also tried with pip: `pip install git+https://github.com/jgrss/geowombat`.
This results in the fiona install failing with 'A GDAL API version must be specified.'

Following the third set of alternate installation instructions [here](https://geowombat.readthedocs.io/en/latest/install_conda.html), (again, slightly different) I get the same fiona error.  I tried setting GDAL_VERSION as an environment variable as instructed, but this led to 'ERROR: Failed building wheel for fiona'. I also tried installing fiona with conda, which worked, but then the pip install failed with another wheel error.

**Comment by mmann1123** [comment]
Ok good to know. For the Fiona error, try installing the binaries from gohylk 
https://www.lfd.uci.edu/~gohlke/pythonlibs/
Please let us know if that resolved it.

**Comment by imagesbyjohnyoung** [comment]
(py38_BIP) C:\Data\EHG_PROJECTS\ehg-bip-wp9\zTestCode>pip install git+https://github.com/jgrss/geowombat
Collecting git+https://github.com/jgrss/geowombat
  Cloning https://github.com/jgrss/geowombat to c:\data\gis\temp\pip-req-build-ai5dlshw
  Running command git clone --filter=blob:none --quiet https://github.com/jgrss/geowombat 'C:\Data\GIS\Temp\pip-req-build-ai5dlshw'
  Resolved https://github.com/jgrss/geowombat to commit 6ca6ef42db1c28e40884c070baf511d63c3924fe
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: geopandas>=0.8.0 in c:\data\py_envs\py38_bip\lib\site-packages (from geowombat==1.11.3) (0.11.1)
Requirement already satisfied: dask[array,dataframe]>=2021.* in c:\data\py_envs\py38_bip\lib\site-packages (from geowombat==1.11.3) (2022.7.1)
Collecting distributed>=2021.*
  Using cached distributed-2022.8.0-py3-none-any.whl (890 kB)
Requirement already satisfied: pandas>=1.* in c:\data\py_envs\py38_bip\lib\site-packages (from geowombat==1.11.3) (1.4.3)
Collecting retry
  Using cached retry-0.9.2-py2.py3-none-any.whl (8.0 kB)
Requirement already satisfied: scipy>=1.5.0 in c:\data\py_envs\py38_bip\lib\site-packages (from geowombat==1.11.3) (1.8.1)
Requirement already satisfied: tqdm>=4.62.0 in c:\data\py_envs\py38_bip\lib\site-packages (from geowombat==1.11.3) (4.64.0)
Requirement already satisfied: joblib>=0.16.0 in c:\data\py_envs\py38_bip\lib\site-packages (from geowombat==1.11.3) (1.1.0)
Requirement already satisfied: scikit-learn>=0.23.0 in c:\data\py_envs\py38_bip\lib\site-packages (from geowombat==1.11.3) (1.1.1)
Requirement already satisfied: numpy>=1.19.0 in c:\data\py_envs\py38_bip\lib\site-packages (from geowombat==1.11.3) (1.22.4+vanilla)
Requirement already satisfied: pyproj>=2.6.0 in c:\data\py_envs\py38_bip\lib\site-packages (from geowombat==1.11.3) (3.3.1)
Requirement already satisfied: shapely>=1.7.0 in c:\data\py_envs\py38_bip\lib\site-packages (from geowombat==1.11.3) (1.8.2)
Requirement already satisfied: xarray>=0.17.0 in c:\data\py_envs\py38_bip\lib\site-packages (from geowombat==1.11.3) (2022.6.0)
Requirement already satisfied: matplotlib>=3.3.0 in c:\data\py_envs\py38_bip\lib\site-packages (from geowombat==1.11.3) (3.5.2)
Collecting opencv-python
  Using cached opencv_python-4.6.0.66-cp36-abi3-win_amd64.whl (35.6 MB)
Requirement already satisfied: cryptography in c:\data\py_envs\py38_bip\lib\site-packages (from geowombat==1.11.3) (37.0.4)
Requirement already satisfied: requests>=2.20.0 in c:\data\py_envs\py38_bip\lib\site-packages (from geowombat==1.11.3) (2.28.1)
Collecting rasterio<2.0.0,>=1.3.0
  Using cached rasterio-1.3.0-cp38-cp38-win_amd64.whl (15.6 MB)
Requirement already satisfied: packaging>=20.0 in c:\data\py_envs\py38_bip\lib\site-packages (from dask[array,dataframe]>=2021.*->geowombat==1.11.3) (21.3)
Requirement already satisfied: pyyaml>=5.3.1 in c:\data\py_envs\py38_bip\lib\site-packages (from dask[array,dataframe]>=2021.*->geowombat==1.11.3) (6.0)
Requirement already satisfied: toolz>=0.8.2 in c:\data\py_envs\py38_bip\lib\site-packages (from dask[array,dataframe]>=2021.*->geowombat==1.11.3) (0.12.0)
Requirement already satisfied: cloudpickle>=1.1.1 in c:\data\py_envs\py38_bip\lib\site-packages (from dask[array,dataframe]>=2021.*->geowombat==1.11.3) (2.1.0)
Requirement already satisfied: partd>=0.3.10 in c:\data\py_envs\py38_bip\lib\site-packages (from dask[array,dataframe]>=2021.*->geowombat==1.11.3) (1.2.0)
Requirement already satisfied: fsspec>=0.6.0 in c:\data\py_envs\py38_bip\lib\site-packages (from dask[array,dataframe]>=2021.*->geowombat==1.11.3) (2022.7.1)
Collecting zict>=0.1.3
  Using cached zict-2.2.0-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: urllib3 in c:\data\py_envs\py38_bip\lib\site-packages (from distributed>=2021.*->geowombat==1.11.3) (1.26.11)
Collecting distributed>=2021.*
  Using cached distributed-2022.7.1-py3-none-any.whl (889 kB)
Collecting tblib>=1.6.0
  Using cached tblib-1.7.0-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: click>=6.6 in c:\data\py_envs\py38_bip\lib\site-packages (from distributed>=2021.*->geowombat==1.11.3) (8.0.3)
Requirement already satisfied: jinja2 in c:\data\py_envs\py38_bip\lib\site-packages (from distributed>=2021.*->geowombat==1.11.3) (3.1.2)
Collecting tornado<6.2,>=6.0.3
  Using cached tornado-6.1-cp38-cp38-win_amd64.whl (422 kB)
Requirement already satisfied: psutil>=5.0 in c:\data\py_envs\py38_bip\lib\site-packages (from distributed>=2021.*->geowombat==1.11.3) (5.9.1)
Collecting msgpack>=0.6.0
  Using cached msgpack-1.0.4-cp38-cp38-win_amd64.whl (62 kB)
Collecting sortedcontainers!=2.0.0,!=2.0.1
  Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Requirement already satisfied: locket>=1.0.0 in c:\data\py_envs\py38_bip\lib\site-packages (from distributed>=2021.*->geowombat==1.11.3) (1.0.0)
Requirement already satisfied: fiona>=1.8 in c:\data\py_envs\py38_bip\lib\site-packages (from geopandas>=0.8.0->geowombat==1.11.3) (1.8.21)
Requirement already satisfied: pyparsing>=2.2.1 in c:\data\py_envs\py38_bip\lib\site-packages (from matplotlib>=3.3.0->geowombat==1.11.3) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\data\py_envs\py38_bip\lib\site-packages (from matplotlib>=3.3.0->geowombat==1.11.3) (1.4.4)
Requirement already satisfied: python-dateutil>=2.7 in c:\data\py_envs\py38_bip\lib\site-packages (from matplotlib>=3.3.0->geowombat==1.11.3) (2.8.2)
Requirement already satisfied: cycler>=0.10 in c:\data\py_envs\py38_bip\lib\site-packages (from matplotlib>=3.3.0->geowombat==1.11.3) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in c:\data\py_envs\py38_bip\lib\site-packages (from matplotlib>=3.3.0->geowombat==1.11.3) (9.2.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\data\py_envs\py38_bip\lib\site-packages (from matplotlib>=3.3.0->geowombat==1.11.3) (4.34.4)
Requirement already satisfied: pytz>=2020.1 in c:\data\py_envs\py38_bip\lib\site-packages (from pandas>=1.*->geowombat==1.11.3) (2022.1)
Requirement already satisfied: certifi in c:\data\py_envs\py38_bip\lib\site-packages (from pyproj>=2.6.0->geowombat==1.11.3) (2022.6.15)
Requirement already satisfied: cligj>=0.5 in c:\data\py_envs\py38_bip\lib\site-packages (from rasterio<2.0.0,>=1.3.0->geowombat==1.11.3) (0.7.2)
Requirement already satisfied: snuggs>=1.4.1 in c:\data\py_envs\py38_bip\lib\site-packages (from rasterio<2.0.0,>=1.3.0->geowombat==1.11.3) (1.4.7)
Requirement already satisfied: affine in c:\data\py_envs\py38_bip\lib\site-packages (from rasterio<2.0.0,>=1.3.0->geowombat==1.11.3) (2.3.1)
Requirement already satisfied: setuptools in c:\data\py_envs\py38_bip\lib\site-packages (from rasterio<2.0.0,>=1.3.0->geowombat==1.11.3) (63.4.2)
Requirement already satisfied: click-plugins in c:\data\py_envs\py38_bip\lib\site-packages (from rasterio<2.0.0,>=1.3.0->geowombat==1.11.3) (1.1.1)
Requirement already satisfied: attrs in c:\data\py_envs\py38_bip\lib\site-packages (from rasterio<2.0.0,>=1.3.0->geowombat==1.11.3) (22.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\data\py_envs\py38_bip\lib\site-packages (from requests>=2.20.0->geowombat==1.11.3) (3.3)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\data\py_envs\py38_bip\lib\site-packages (from requests>=2.20.0->geowombat==1.11.3) (2.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\data\py_envs\py38_bip\lib\site-packages (from scikit-learn>=0.23.0->geowombat==1.11.3) (3.1.0)
Requirement already satisfied: colorama in c:\data\py_envs\py38_bip\lib\site-packages (from tqdm>=4.62.0->geowombat==1.11.3) (0.4.5)
Requirement already satisfied: cffi>=1.12 in c:\data\py_envs\py38_bip\lib\site-packages (from cryptography->geowombat==1.11.3) (1.15.1)
Collecting py<2.0.0,>=1.4.26
  Using cached py-1.11.0-py2.py3-none-any.whl (98 kB)
Requirement already satisfied: decorator>=3.4.2 in c:\data\py_envs\py38_bip\lib\site-packages (from retry->geowombat==1.11.3) (5.1.1)
Requirement already satisfied: pycparser in c:\data\py_envs\py38_bip\lib\site-packages (from cffi>=1.12->cryptography->geowombat==1.11.3) (2.21)
Requirement already satisfied: munch in c:\data\py_envs\py38_bip\lib\site-packages (from fiona>=1.8->geopandas>=0.8.0->geowombat==1.11.3) (2.5.0)
Requirement already satisfied: gdal~=3.4.3 in c:\data\py_envs\py38_bip\lib\site-packages (from fiona>=1.8->geopandas>=0.8.0->geowombat==1.11.3) (3.4.3)
Requirement already satisfied: six>=1.7 in c:\data\py_envs\py38_bip\lib\site-packages (from fiona>=1.8->geopandas>=0.8.0->geowombat==1.11.3) (1.16.0)
Collecting heapdict
  Using cached HeapDict-1.0.1-py3-none-any.whl (3.9 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\data\py_envs\py38_bip\lib\site-packages (from jinja2->distributed>=2021.*->geowombat==1.11.3) (2.1.1)
Building wheels for collected packages: geowombat
  Building wheel for geowombat (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for geowombat (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [128 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      creating build\lib.win-amd64-cpython-38\geowombat
      copying src\geowombat\config.py -> build\lib.win-amd64-cpython-38\geowombat
      copying src\geowombat\handler.py -> build\lib.win-amd64-cpython-38\geowombat
      copying src\geowombat\__init__.py -> build\lib.win-amd64-cpython-38\geowombat
      creating build\lib.win-amd64-cpython-38\geowombat\backends
      copying src\geowombat\backends\dask_.py -> build\lib.win-amd64-cpython-38\geowombat\backends
      copying src\geowombat\backends\gdal_.py -> build\lib.win-amd64-cpython-38\geowombat\backends
      copying src\geowombat\backends\rasterio_.py -> build\lib.win-amd64-cpython-38\geowombat\backends
      copying src\geowombat\backends\xarray_.py -> build\lib.win-amd64-cpython-38\geowombat\backends
      copying src\geowombat\backends\xarray_rasterio_.py -> build\lib.win-amd64-cpython-38\geowombat\backends
      copying src\geowombat\backends\zarr_.py -> build\lib.win-amd64-cpython-38\geowombat\backends
      copying src\geowombat\backends\__init__.py -> build\lib.win-amd64-cpython-38\geowombat\backends
      creating build\lib.win-amd64-cpython-38\geowombat\core
      copying src\geowombat\core\api.py -> build\lib.win-amd64-cpython-38\geowombat\core
      copying src\geowombat\core\base.py -> build\lib.win-amd64-cpython-38\geowombat\core
      copying src\geowombat\core\conversion.py -> build\lib.win-amd64-cpython-38\geowombat\core
      copying src\geowombat\core\geoxarray.py -> build\lib.win-amd64-cpython-38\geowombat\core
      copying src\geowombat\core\io.py -> build\lib.win-amd64-cpython-38\geowombat\core
      copying src\geowombat\core\parallel.py -> build\lib.win-amd64-cpython-38\geowombat\core
      copying src\geowombat\core\properties.py -> build\lib.win-amd64-cpython-38\geowombat\core
      copying src\geowombat\core\series.py -> build\lib.win-amd64-cpython-38\geowombat\core
      copying src\geowombat\core\sops.py -> build\lib.win-amd64-cpython-38\geowombat\core
      copying src\geowombat\core\stac.py -> build\lib.win-amd64-cpython-38\geowombat\core
      copying src\geowombat\core\util.py -> build\lib.win-amd64-cpython-38\geowombat\core
      copying src\geowombat\core\vi.py -> build\lib.win-amd64-cpython-38\geowombat\core
      copying src\geowombat\core\windows.py -> build\lib.win-amd64-cpython-38\geowombat\core
      copying src\geowombat\core\__init__.py -> build\lib.win-amd64-cpython-38\geowombat\core
      creating build\lib.win-amd64-cpython-38\geowombat\data
      copying src\geowombat\data\__init__.py -> build\lib.win-amd64-cpython-38\geowombat\data
      creating build\lib.win-amd64-cpython-38\geowombat\ml
      copying src\geowombat\ml\classifiers.py -> build\lib.win-amd64-cpython-38\geowombat\ml
      copying src\geowombat\ml\transformers.py -> build\lib.win-amd64-cpython-38\geowombat\ml
      copying src\geowombat\ml\__init__.py -> build\lib.win-amd64-cpython-38\geowombat\ml
      creating build\lib.win-amd64-cpython-38\geowombat\moving
      copying src\geowombat\moving\__init__.py -> build\lib.win-amd64-cpython-38\geowombat\moving
      creating build\lib.win-amd64-cpython-38\geowombat\radiometry
      copying src\geowombat\radiometry\angles.py -> build\lib.win-amd64-cpython-38\geowombat\radiometry
      copying src\geowombat\radiometry\brdf.py -> build\lib.win-amd64-cpython-38\geowombat\radiometry
      copying src\geowombat\radiometry\mask.py -> build\lib.win-amd64-cpython-38\geowombat\radiometry
      copying src\geowombat\radiometry\qa.py -> build\lib.win-amd64-cpython-38\geowombat\radiometry
      copying src\geowombat\radiometry\sixs.py -> build\lib.win-amd64-cpython-38\geowombat\radiometry
      copying src\geowombat\radiometry\sr.py -> build\lib.win-amd64-cpython-38\geowombat\radiometry
      copying src\geowombat\radiometry\topo.py -> build\lib.win-amd64-cpython-38\geowombat\radiometry
      copying src\geowombat\radiometry\__init__.py -> build\lib.win-amd64-cpython-38\geowombat\radiometry
      creating build\lib.win-amd64-cpython-38\geowombat\tasks
      copying src\geowombat\tasks\pipeline.py -> build\lib.win-amd64-cpython-38\geowombat\tasks
      copying src\geowombat\tasks\__init__.py -> build\lib.win-amd64-cpython-38\geowombat\tasks
      creating build\lib.win-amd64-cpython-38\geowombat\util
      copying src\geowombat\util\plotting.py -> build\lib.win-amd64-cpython-38\geowombat\util
      copying src\geowombat\util\web.py -> build\lib.win-amd64-cpython-38\geowombat\util
      copying src\geowombat\util\__init__.py -> build\lib.win-amd64-cpython-38\geowombat\util
      running egg_info
      writing src\geowombat.egg-info\PKG-INFO
      writing dependency_links to src\geowombat.egg-info\dependency_links.txt
      writing requirements to src\geowombat.egg-info\requires.txt
      writing top-level names to src\geowombat.egg-info\top_level.txt
      reading manifest file 'src\geowombat.egg-info\SOURCES.txt'
      adding license file 'LICENSE.txt'
      adding license file 'AUTHORS.txt'
      writing manifest file 'src\geowombat.egg-info\SOURCES.txt'
      copying src\geowombat\config.ini -> build\lib.win-amd64-cpython-38\geowombat
      creating build\lib.win-amd64-cpython-38\geowombat\bin
      copying src\geowombat\bin\ESPA.tar.gz -> build\lib.win-amd64-cpython-38\geowombat\bin
      copying src\geowombat\data\LC08_L2SP_224078_20200127_02_T1_LC08_L2SP_224078_20200127_20200823_02_T1_MTL.txt -> build\lib.win-amd64-cpython-38\geowombat\data
      copying src\geowombat\data\LC08_L1TP_224077_20200518_20200518_01_RT_B2.TIF -> build\lib.win-amd64-cpython-38\geowombat\data
      copying src\geowombat\data\LC08_L1TP_224077_20200518_20200518_01_RT_B3.TIF -> build\lib.win-amd64-cpython-38\geowombat\data
      copying src\geowombat\data\LC08_L1TP_224077_20200518_20200518_01_RT_B4.TIF -> build\lib.win-amd64-cpython-38\geowombat\data
      copying src\geowombat\data\LC08_L1TP_224078_20200518_20200518_01_RT.TIF -> build\lib.win-amd64-cpython-38\geowombat\data
      copying src\geowombat\data\LC08_L1TP_224078_20200518_20200518_01_RT_B2.TIF -> build\lib.win-amd64-cpython-38\geowombat\data
      copying src\geowombat\data\LC08_L1TP_224078_20200518_20200518_01_RT_B3.TIF -> build\lib.win-amd64-cpython-38\geowombat\data
      copying src\geowombat\data\LC08_L1TP_224078_20200518_20200518_01_RT_B4.TIF -> build\lib.win-amd64-cpython-38\geowombat\data
      copying src\geowombat\data\rgbn.tif -> build\lib.win-amd64-cpython-38\geowombat\data
      copying src\geowombat\data\rgbn_20160101.tif -> build\lib.win-amd64-cpython-38\geowombat\data
      copying src\geowombat\data\rgbn_20160401.tif -> build\lib.win-amd64-cpython-38\geowombat\data
      copying src\geowombat\data\rgbn_20160517.tif -> build\lib.win-amd64-cpython-38\geowombat\data
      copying src\geowombat\data\rgbn_20170203.tif -> build\lib.win-amd64-cpython-38\geowombat\data
      copying src\geowombat\data\rgbn_suba.tif -> build\lib.win-amd64-cpython-38\geowombat\data
      copying src\geowombat\data\rgbn_subb.tif -> build\lib.win-amd64-cpython-38\geowombat\data
      copying src\geowombat\data\LC08_L1TP_224078_20200518_20200518_01_RT_points.gpkg -> build\lib.win-amd64-cpython-38\geowombat\data
      copying src\geowombat\data\LC08_L1TP_224078_20200518_20200518_01_RT_polygons.gpkg -> build\lib.win-amd64-cpython-38\geowombat\data
      copying src\geowombat\data\srtm30m_bounding_boxes.gpkg -> build\lib.win-amd64-cpython-38\geowombat\data
      copying src\geowombat\data\mgrs.tar.gz -> build\lib.win-amd64-cpython-38\geowombat\data
      copying src\geowombat\data\wrs2.tar.gz -> build\lib.win-amd64-cpython-38\geowombat\data
      copying src\geowombat\moving\_moving.c -> build\lib.win-amd64-cpython-38\geowombat\moving
      copying src\geowombat\radiometry\_fusion.c -> build\lib.win-amd64-cpython-38\geowombat\radiometry
      running build_ext
      building 'geowombat.moving._moving' extension
      creating build\temp.win-amd64-cpython-38
      creating build\temp.win-amd64-cpython-38\Release
      creating build\temp.win-amd64-cpython-38\Release\src
      creating build\temp.win-amd64-cpython-38\Release\src\geowombat
      creating build\temp.win-amd64-cpython-38\Release\src\geowombat\moving
      "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Data\GIS\Temp\pip-build-env-1kuy61fv\overlay\Lib\site-packages\numpy\core\include -Ic:\data\PY_ENVS\py38_BIP\include -IC:\Python38\include -IC:\Python38\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include" /Tcsrc/geowombat/moving/_moving.c /Fobuild\temp.win-amd64-cpython-38\Release\src/geowombat/moving/_moving.obj -fopenmp
      cl : Command line warning D9002 : ignoring unknown option '-fopenmp'
      _moving.c
      C:\Python38\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory      C:\Data\GIS\Temp\pip-build-env-1kuy61fv\overlay\Lib\site-packages\setuptools\command\build_py.py:153: SetuptoolsDeprecationWarning:     Installing 'geowombat.bin' as data is deprecated, please list it in `packages`.
          !!


          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'geowombat.bin' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'geowombat.bin' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'geowombat.bin' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.


      !!

        check.warn(importable)
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for geowombat
Failed to build geowombat
ERROR: Could not build wheels for geowombat, which is required to install pyproject.toml-based projects

**Comment by mmann1123** [comment]
If you don't already have Microsoft Visual C++ installed do so from the following link. Make sure you match the correct version for the Python you have installed. https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_14.0_standalone:_Build_Tools_for_Visual_Studio_2017_.28x86.2C_x64.2C_ARM.2C_ARM64.29
