### ISSUE TITLE
ml install

### ISSUE THREAD

**Issue by mmann1123** [jgrss/geowombat#218]
Trying to help resolve #216  but running into a likely easily fixed issue. As you suggested a while back I can do ` pip install --user -e ."[ml]"` in my dockerfile. However I am getting an error now with the your sklearn fork. Maybe there's an easy work around?

```
RUN git clone https://github.com/jgrss/geowombat.git --branch jgrss/scales_216

RUN cd geowombat && pip install --user -e ."[ml]"
```
```
ERROR: Invalid requirement: 'sklearn-xarray@ git+https://github.com/jgrss/sklearn-xarray.git; extra == "ml"'
The command '/bin/sh -c cd geowombat && pip install --user -e ."[ml]"' returned a non-zero code: 1
```

**Comment by jgrss** [comment]
Hmm, is your `pip` up to date? And does removing the strings help?
```commandline
RUN pip install -U pip
RUN cd geowombat && pip install -e .[ml]
```

**Comment by mmann1123** [comment]
Huh yep that was it, figured since i was pulling the latest ubuntu docker image I didn't need to worry about that... apparently I did.
