### ISSUE TITLE
crs error

### ISSUE THREAD

**Issue by b7j** [jgrss/geowombat#23]
return the following error, even when using geowombat rgbn test image:

rasterio.errors.CRSError: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.

**Comment by jgrss** [comment]
Hi @b7j, this is a rasterio issue that can be found [here](https://rasterio.readthedocs.io/en/latest/faq.html) and [here](https://github.com/mapbox/rasterio/issues/1539).

You should have the environment variable `GDAL_DATA` set to the directory that has files similar to:

```
bag_template.xml
compdcs.csv
coordinate_axis.csv
datum_shift.csv
default.rsc
eedaconf.json
ellipsoid.csv
epsg.wkt
esri_epsg.wkt
esri_extra.wkt
esri_StatePlane_extra.wkt
esri_Wisconsin_extra.wkt
gcs.csv
gcs.override.csv
gdal_datum.csv
gdalicon.png
GDALLogoBW.svg
GDALLogoColor.svg
GDALLogoGS.svg
gdalvrt.xsd
geoccs.csv
gmlasconf.xml
gmlasconf.xsd
gml_registry.xml
gt_datum.csv
gt_ellips.csv
header.dxf
inspire_cp_BasicPropertyUnit.gfs
inspire_cp_CadastralBoundary.gfs
inspire_cp_CadastralParcel.gfs
inspire_cp_CadastralZoning.gfs
jpfgdgml_AdmArea.gfs
jpfgdgml_AdmBdry.gfs
jpfgdgml_AdmPt.gfs
jpfgdgml_BldA.gfs
jpfgdgml_BldL.gfs
jpfgdgml_Cntr.gfs
jpfgdgml_CommBdry.gfs
jpfgdgml_CommPt.gfs
jpfgdgml_Cstline.gfs
jpfgdgml_ElevPt.gfs
jpfgdgml_GCP.gfs
jpfgdgml_LeveeEdge.gfs
jpfgdgml_RailCL.gfs
jpfgdgml_RdArea.gfs
jpfgdgml_RdASL.gfs
jpfgdgml_RdCompt.gfs
jpfgdgml_RdEdg.gfs
jpfgdgml_RdMgtBdry.gfs
jpfgdgml_RdSgmtA.gfs
jpfgdgml_RvrMgtBdry.gfs
jpfgdgml_SBAPt.gfs
jpfgdgml_SBArea.gfs
jpfgdgml_SBBdry.gfs
jpfgdgml_WA.gfs
jpfgdgml_WL.gfs
jpfgdgml_WStrA.gfs
jpfgdgml_WStrL.gfs
netcdf_config.xsd
nitf_spec.xml
nitf_spec.xsd
ogrvrt.xsd
osmconf.ini
ozi_datum.csv
ozi_ellips.csv
pci_datum.txt
pci_ellips.txt
pcs.csv
pcs.override.csv
pds4_template.xml
plscenesconf.json
prime_meridian.csv
projop_wparm.csv
ruian_vf_ob_v1.gfs
ruian_vf_st_uvoh_v1.gfs
ruian_vf_st_v1.gfs
ruian_vf_v1.gfs
s57agencies.csv
s57attributes.csv
s57expectedinput.csv
s57objectclasses.csv
seed_2d.dgn
seed_3d.dgn
stateplane.csv
trailer.dxf
unit_of_measure.csv
vdv452.xml
vdv452.xsd
vertcs.csv
vertcs.override.csv
```

On Linux, installing GDAL with apt puts `GDAL_DATA` in `/usr/share/gdal`. On Windows, you might have to set the environment variable manually. Or, [conda](https://github.com/conda-forge/gdal-feedstock/issues/54) might help address the issue.

**Comment by b7j** [comment]
Thanks Jordan, Jason here, not sure why im getting this issue now, i thought it was a corrupt conda install but with a new env and a reinstall of everything problem persisted. Will take a look at your suggestions.

**Comment by b7j** [comment]
Still stuggling with how to set the conda env variable, found the path to the directory but carnt figure out  how to set the GDAL_DATA variable to that path?

**Comment by b7j** [comment]
likely gdal version problem
