### ISSUE TITLE
Resample leaves no data blocks into Sentinel2 image

### ISSUE THREAD

**Issue by georgeboldeanu** [jgrss/geowombat#236]
Hello! 
I try to resample a list of sentinel 2 bands from native 20m resolution to 10m resolution. In the process i encounter the next issue with existence of no data rectangles into image as inspected into QGIS. (down below)
![geowombat](https://user-images.githubusercontent.com/34105846/214304102-214b57e3-1c12-49c8-b01d-ba0d726b5318.PNG)

My piece of code snippet is: 

```
list_20_n=[] ###list with 20m resolution Sentinel 2 bands
for i in list_20_n:
        with gw.config.update(ref_crs='EPSG:3844', ref_res=10):
            with gw.open(i, resampling='bilinear') as src:
                        print(src.transform)
                        print(src.crs)
                        print(src.resampling)
                        print(src.res)
                        print(src.name,'nume')
                        print(src.shape)
                        src.gw.to_raster(
                            export_path+i[-11:-4]+'.tif',
                            verbose=1,
                            n_workers=8,  
                            n_threads=16,
                            n_chunks=256
                            )
                        src.close()
```

I really can't figure it out, I was thinking that first there was some issue with the bands, but thats not the case. I also thought that n_chunks param was off, but tried without them, still no change. I will attach a S2_05_20m band as a wetransfer link: https://we.tl/t-gab4jg4VM1

**Comment by mmann1123** [comment]
I think there's an issue with to_raster. Can you set the number of workers
to 1 and leave out threads and chunks

**Comment by georgeboldeanu** [comment]
@mmann1123 Yes, setting the number of workers to 1 resolve the issue. Indeed affects the speed, but exports the expected raster. Thank you. I hope in the future will be resolved. Cheers!
