### ISSUE TITLE
conda-forge issues

### ISSUE THREAD

**Issue by mmann1123** [jgrss/geowombat#261]
Hey looks like 2.1.7 is failing for linux python 3.8 for some reason. I looked through all the changes in 3.1.7 and I am having a hard time figuring what might be failing. I noticed you updated the version of python 3.8 you used in the CI tests in .github/workflows/ci.yml 

```
  -        python-version: 3.8.12
  +        python-version: 3.8.15
```
 maybe conda-forge isn't getting the message?  Should we set requirements to python>3.8.15? 

In all honesty the errors make no sense to me, but wondering if  you recognize anything.  I am assuming its the issue above but hard to say. 
[see conda-forge test fails here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=684482&view=logs&jobId=5c51a9b2-339f-5e52-ee1c-93d36cabd2b6&j=5c51a9b2-339f-5e52-ee1c-93d36cabd2b6&t=02204410-6da5-55b7-5113-a6a352ef8a30)

**Comment by jgrss** [comment]
Where do you pin the `conda` Python requirement?

**Comment by mmann1123** [comment]
it all seems to be pulled in from your module requirements (I think).  The only thing that we needed to get together for conda-forge was this [recipe](https://github.com/conda-forge/geowombat-feedstock/blob/main/recipe/meta.yaml)

**Comment by mmann1123** [comment]
Ok looks like something got pushed to conda-forge last night. Builds are now failing on linux, and osx.  For example [here](
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=689916&view=logs&j=4f922444-fdfe-5dcf-b824-02f86439ef14&t=b2a8456a-fb11-5506-ca32-5ccd32538dc0&l=206)

Looks like it can't find freetype 2.5.* needed by graphviz-2.38.0-0

Assuming we need to add graphviz to requirements, but I thought that came with dask.

**Comment by jgrss** [comment]
I think `graphviz` does get installed via one of the other dependencies. The error looks to be coming from `graphviz` itself. See [here](https://github.com/ImageMagick/ImageMagick/issues/5286).

**Comment by jgrss** [comment]
@mmann1123 https://github.com/conda/conda/issues/1851#issuecomment-225591223

**Comment by mmann1123** [comment]
This is a really old issue. Not sure why it would be breaking now.  I will rerun the build tests, maybe graphviz broke something on their recipe? If not I'll open an issue with graphviz.

**Comment by mmann1123** [comment]
Interestingly the graphviz error resolved for linux NOT osx, and we replaced with [this](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=689916&view=logs&j=5c51a9b2-339f-5e52-ee1c-93d36cabd2b6&t=86db673d-28f1-5516-b5f3-125685f56516&l=206)

`- package proj-9.1.1-h93bde94_0 requires libtiff >=4.4.0,<4.5.0a0, but none of the providers can be installed`

OSX still has the graphviz error.

**Comment by mmann1123** [comment]
Ok coming back to this since your push of 2.1.8 didn't resolve the issue.
Focusing on this error for now:

`nothing provides freetype 2.5.* needed by graphviz-2.38.0-0`

This is all very odd, it seems like `graphviz` maybe has multple wrappers for python.  Oddly the equivalent of `pip install graphviz` is `conda install python-graphviz`.  Maybe its to keep conda for install the java (or whatever version). 

The thing that is warping my mind a bit is that `mamba create -n test python=3.9 dask python-graphviz -c conda-forge` installs `graphviz 8.0.3`, and `pip install graphviz` installs `graphviz 0.20.1`. 

My assumption is that graphviz 8.0.3 in conda is equivalent to 0.20.1 in pip.  

Its very odd the graphviz 2.38 is getting called here. Dask is currently using graphviz 8.03.   I did notice that graphviz version updates aren't getting pushed to conda (or elsewhere??)  https://anaconda.org/conda-forge/graphviz


The only easy solution I can think of here is to see if we can ensure dask installs the required graphviz components. For instance, is the following also installing the optional dependencies?? 

dask[array,dataframe]>=2023.1.0

**Comment by jgrss** [comment]
Where do we specify the Python version range for the `conda` recipe? It's pinning the upper limit to [`v3.9.0a0`](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=689916&view=logs&j=5c51a9b2-339f-5e52-ee1c-93d36cabd2b6&t=86db673d-28f1-5516-b5f3-125685f56516&l=254). Not sure if that's related, though. 

Also, as you probably saw, there's [a conflict with `proj` and `libtiff`](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=689916&view=logs&j=5c51a9b2-339f-5e52-ee1c-93d36cabd2b6&t=86db673d-28f1-5516-b5f3-125685f56516&l=269). However, it looks like the appropriate version of [`libtiff`](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=689916&view=logs&j=5c51a9b2-339f-5e52-ee1c-93d36cabd2b6&t=86db673d-28f1-5516-b5f3-125685f56516&l=111) should be installed.

**Comment by mmann1123** [comment]
I have been making some progress (started fresh)
https://github.com/conda-forge/geowombat-feedstock/pull/89

**Comment by mmann1123** [comment]
@jgrss One issue that has come up is the use of `with tempfile.TemporaryDirectory()` for the windows builds for conda. Seems like it might not be compatable on windows. This come up with at least `test_write` and `test_nodata`.  See error here: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=693951&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=1119

**Comment by mmann1123** [comment]
@jgrss I am trying to move everything over to conda-forge and thus need to become the maintainer of our build of sklearn-xarray, they are requesting that you add a comment to the following PR that you are OK with being a maintainer (I will do the work, but want you to have a say too). 

https://github.com/conda-forge/staged-recipes/pull/22655

**Comment by mmann1123** [comment]
This issue is resolved.
