### ISSUE TITLE
conda optional extras

### ISSUE THREAD

**Issue by mmann1123** [jgrss/geowombat#266]
I have been working hard on getting the optional extras sorted for conda. I think I am getting close (for instance see [readme](https://github.com/conda-forge/geowombat-feedstock/blob/64d44e3f39f58c613d16a5bb0c170bac8f5cccc6/README.md)) There are a few issues across OSs (e.g. jax isn't available for windows through conda), maybe worth taking a look at the [recipe](https://github.com/conda-forge/geowombat-feedstock/pull/97) to see if you have an issues with how I have it set up.

**Comment by mmann1123** [comment]
@jgrss I have been working on getting the optional extras into conda feedstock.  Please check it out!

https://github.com/mmann1123/geowombat-feedstock/tree/optional_extras2

**Comment by jgrss** [comment]
Hey @mmann1123 this sounds great. Could you make a draft PR so that I see the additions/changes? Or else drop a link to the optional extras.

**Comment by mmann1123** [comment]
Here's the meta for the optional extras: 
https://github.com/mmann1123/geowombat-feedstock/blob/optional_extras2/recipe/meta.yaml

**Comment by jgrss** [comment]
This is great. How do you install with extras using `conda`?

**Comment by mmann1123** [comment]
It should be base on the table [here](https://github.com/conda-forge/geowombat-feedstock/blob/fe92613e8324cd4734521ef8f82216943312290d/README.md)

for example:
`mamba install geowombat-ml -c conda-forge`
or:
`mamba install geowombat[ml] -c conda-forge`


I have been trying to mirror the install of ray (which has lots of optional extas)
[feedstock here](https://github.com/conda-forge/ray-packages-feedstock/blob/main/recipe/meta.yaml)
[install instructions](https://docs.ray.io/en/latest/ray-overview/installation.html)

**Comment by mmann1123** [comment]
Quick question, you have jax installed in the "test" extras and the only test calling jax that I'm finding is:

`   - pytest tests/test_series.py `

Should jax just be in test???

**Comment by mmann1123** [comment]
Although we should find the right place for `jax` I think we are ready to push the optional extras branch for the conda feedstock.  You ok with that?  @jgrss

**Comment by jgrss** [comment]
> Although we should find the right place for `jax` I think we are ready to push the optional extras branch for the conda feedstock.  You ok with that?  @jgrss 

Yeah, it looks good to me.

**Comment by jgrss** [comment]
> @jgrss  Quick question, you have jax installed in the "test" extras and the only test calling jax that I'm finding is:
> 
> `   - pytest tests/test_series.py `
> 
> Should jax just be in test??? Or is it better in performance? 

I think we need to have another look at that time module.

**Comment by mmann1123** [comment]
I was thinking performance.  That being said i just started using the apply
functions with jax numpy and its been pretty impressive. The usage isn't
intuitive but it's fast.

**Comment by mmann1123** [comment]
@jgrss Oddly, I made a trivial change to the conda feedstock and triggered an issue.

Seems like geowombat-test option isn't installing correctly in OSX and Linux,  I can't really see what the issue is other than that it isn't importing geowombat, which is odd.  Take a look at the error, maybe I am missing something?
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=754393&view=logs&j=4b3757f9-99c5-5891-6c0c-93d7030cdf7d&t=f047df50-a233-5ae9-bf8f-c7dd8e5684ad&l=3789

**Comment by mmann1123** [comment]
@jgrss I had to skip the build for tests for python 3.8, and jax for windows. 

I am going to merge the optional extras feedstock now, `conda install geowombat` should still work but we should think about updating the install docs.

**Comment by mmann1123** [comment]
All optional extras are now available through conda-forge please see [feedstock docs here](https://github.com/conda-forge/geowombat-feedstock).
