### ISSUE TITLE
Expand pinned python version

### ISSUE THREAD

**Issue by rdenham** [jgrss/geowombat#276]
I see that you have pinned python to `python_requires = >=3.8,<=3.9.16`.

Just wondering if there is a reason that it needs to be '<3.9.16', or is that just because that's the most recent version you have tested it with?  We updated our python to the most [recent 3.9 verson](https://www.python.org/downloads/release/python-3917/) which broke our install script. I doubt though that there is any breaking changes in that update.

We'd also prefer to be using python 3.10, have you tested gw with this?

Finally, have you considered distributing the cython files with your source so that it is possible to build geowombat from sdist tar.gz file. This would help if someone wanted to build a wheel using [python build](https://pypa-build.readthedocs.io/en/latest/)

I think that to do so, you could just add 

```sh
    moving/_moving.pyx
    util/percentiles.pxd
``` 

to the `[options.package_data]` section in your `setup.cfg` file.

**Comment by jgrss** [comment]
Hi @rdenham, I have not tested on 3.10, but I am happy to expand the upper Python version if tests pass.

Regarding the Cython .so files, we can certainly add those to the `setup.cfg` file.
