### ISSUE TITLE
Failed to Install Geowombat on pip and conda

### ISSUE THREAD

**Issue by ShabaniMagawila** [jgrss/geowombat#279]
Hello folks,
I having the problem to Install Geowombat by using both pip and anaconda. I got some errors, and I post them here below. Please anyone to assist me the whole process.
1. Using Jupyter Lab with Pip command
I use this command to install: 'pip install geowombat
![image](https://github.com/jgrss/geowombat/assets/36422571/81ff1429-7a13-4ce3-81bf-0f9f2723a926)
I use this code: 'pip install git+https://github.com/jgrss/geowombat'
![image](https://github.com/jgrss/geowombat/assets/36422571/32303c7f-d3a4-4bf1-9e48-c38986396ef4)

2. Installing using Anaconda Prompt: Jupyter Notebook
I use this code: 'conda install geowombat'
![image](https://github.com/jgrss/geowombat/assets/36422571/b77ab0a1-87e6-4e33-b943-90eefc291181)

**Comment by ShabaniMagawila** [comment]
![image](https://github.com/jgrss/geowombat/assets/36422571/c35de3ab-fba5-4f0c-905a-b8d4a8a8e682)
With conda

**Comment by mmann1123** [comment]
1) for pip you will need to set up a virtual environment with 3.8<=py<=3.10. 3.11 is not supported yet. 

2) conda takes a long time to solve environments, but it should work. Make sure you set up a conda env with the desired python version

> conda create -gw_env python=3.10 geowombat -c conda-forge
> conda activate gw_env 
> python

**Comment by jgrss** [comment]
@ShabaniMagawila following on @mmann1123's answer, if you do not want to use `conda`, `pyenv` is a good option. With `pyenv`, you could install a specific version of Python and then install geowombat inside that environment.

List available Python versions
```commandline
pyenv install --list
```
Install Python 3.10
```commandline
pyenv install 3.10.12
```

Create a virtual environment with Python 3.10 (venv.gw is the new environment name)
```commandline
pyenv virtualenv 3.10.12 venv.gw
```
Activate the virtual environment
```commandline
pyenv activate venv.gw
```
Install geowombat
```commandline
(venv.gw) pip install git+https://github.com/jgrss/geowombat
```
Exit the virtual environment
```commandline
pyenv deactivate
```

**Comment by twnawrocki** [comment]
Even using Python 3.10.12 in a fresh Miniconda installation on Windows 11, conda cannot solve the environment for geowombat.

`conda create -n gw_env python=3.10 geowombat -c conda-forge`

Attempting the process with python 3.8 or 3.9 fails as well. Dependencies (rasterio, rioxarray, etc.) do not encounter any issues. I believe there is a legitimate issue here that is not related to using a python version that is not yet supported.

**Comment by mmann1123** [comment]
huh... that is surprising given the it passes all the build tests [here](https://github.com/conda-forge/geowombat-feedstock). Good to know.  I will try to take a look at it on my work computer.  But be patient with us. We are just 2 guys doing this in our free time.

**Comment by twnawrocki** [comment]
@mmann1123 Absolutely. I intended my above post only as an FYI; the issue may not be worth looking into given functioning alternatives. The situation may also be indicative of a problem or bug in the classic solver. Regardless, I greatly appreciate the work that you and @jgrss are doing!

@ShabaniMagawila and others who may encounter a problem when trying to install geowombat through conda, I suggest the switching to the [libmamba solver](https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community).

```
conda update -n base conda
conda install -n base conda-libmamba-solver
conda config --set solver libmamba

conda create -n gw_env python=3.10 geowombat
```

**Comment by ShabaniMagawila** [comment]
Hello friends,
Thanks for your help, in one way or another you direct me into the solution to my problem above. I like to inform you that your options made me to solve the problem. My sincere thanks reach out to you folks, I would like also to share how I managed to solve this problem. Thanks

![image](https://github.com/jgrss/geowombat/assets/36422571/53fa7581-0e89-40a6-8d7c-2b416331c5d8)

**Comment by ShabaniMagawila** [comment]
Step 1: Install Anaconda
Make sure to install Anaconda to the directory that doesnt have a space in between, see below image, the user "Shabani Magawila" has space in between. So avoid that. 
![image](https://github.com/jgrss/geowombat/assets/36422571/a0f36657-b0b0-4ad3-a5f0-e21d03cbf34f)

You can managed this by either install Anaconda to other Directory like in local disk "C:/ProgramData" or by create a new Window user with no space in between, like below image.
![image](https://github.com/jgrss/geowombat/assets/36422571/67bde4c3-a799-4995-ada8-82134f3cc3d1)

Step 2: Create Python Environment with appropriate specificification
Remember geowombat works with Pythom 3.10, so you have to create environment with python==3.10, for me I created environment called "spatial".
![image](https://github.com/jgrss/geowombat/assets/36422571/b34bb60b-5c84-47c7-9e82-2fc8114b2876)
with python version 3.10.12
![image](https://github.com/jgrss/geowombat/assets/36422571/b723fd5e-3092-4686-96b8-6041f11d53de)

Step 3: Add "conda-forge" channel to the conda environment 
First, make sure to activate your environment as base env. Then add conda-forge with below command, see [more](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge)
![image](https://github.com/jgrss/geowombat/assets/36422571/3fb7927a-ca0b-4254-808f-8e0ab00fabb4)
See below, I have 3 channels added into my environment.
![image](https://github.com/jgrss/geowombat/assets/36422571/74aee936-ecdd-40b1-a118-6c4c30a52622)

Step 4: Install packages through conda-forge (e.g: GDAL)
Before to install any package in the conda-forge, make sure to set "conda-forge" as default channel by bring it on top of others, use this command below. See [more](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html)
![image](https://github.com/jgrss/geowombat/assets/36422571/82bf79ae-6080-46b3-b0ad-581c98afa31b)

Then install "GDAL" by using conda-forge command
![image](https://github.com/jgrss/geowombat/assets/36422571/4ab957df-63cd-4bb0-b53a-ef4dd2795119)

Step 5: Install Geowombat
Finally, use pip command to install geowombat, you're done!
![image](https://github.com/jgrss/geowombat/assets/36422571/fba40409-171a-408c-bfea-bbb53a5889b7)

Happy Learning!

**Comment by mmann1123** [comment]
Hey all, `conda create -n test geowombat -c conda-forge` is working fine on my windows computer - as it is on the conda-forge build pipelines. 

As a general rule I highly recommend using [mambaforge](https://github.com/conda-forge/miniforge#mambaforge) instead of conda (although it looks like the new mamba style solver might resolve some of the lag).   

@twnawrocki  Did you manage to get it installed? If not, please send some details on the error and maybe I can point you in the right direction.

**Comment by twnawrocki** [comment]
@mmann1123 Yes, my install worked with the libmamba solver (and I tested with success for mamba and pip as well). Interesting that the classic conda solver succeeds on your machine (and on the conda-forge pipelines). This seems like a potential bug in the classic solver itself. No objections from me if you'd like to close this issue.

**Comment by mmann1123** [comment]
Good to hear it is working, odd about the classic solver

**Comment by ShabaniMagawila** [comment]
Thanks Michael
