### ISSUE TITLE
Requirement differences between package & conda-forge

### ISSUE THREAD

**Issue by DManowitz** [jgrss/geowombat#280]
According to the setup.cfg file for v.2.1.10, the numpy dependency is `numpy>=1.19.0`.  However, on conda-forge, the numpy dependency is `numpy>=1.24.4`.  Do you know why this is?

**Comment by jgrss** [comment]
Thanks for raising this. I don't know why conda-forge is pinning a higher version (@mmann1123). However, we can do some testing to see if we can either raise numpy in the github repo or lower numpy in conda-forge.

**Comment by DManowitz** [comment]
If you can keep the lower numpy bound and figure how to get it to work correctly on conda-forge, that would be much appreciated.

**Comment by DManowitz** [comment]
According to [meta.yaml](https://github.com/conda-forge/geowombat-feedstock/blob/main/recipe/meta.yaml) in the geowombat conda-forge feedstock, under `run`, it has `{{ pin_compatible('numpy') }}`.  According to [this file](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml#L631), it looks like that should correspond to numpy >=1.21.  However, if the most recent version of geowombat actually works with `numpy >=1.19.0`, perhaps the `run` section of the meta.yaml file in the geowombat conda-forge feedstock should just have `numpy >=1.19.0`.

**Comment by jgrss** [comment]
I agree, unless we have a specific reason for increasing the `numpy` version then I think we should leave it at `>=1.19.0` to give users more flexibility.

I increased the lower version to `>=1.24.4` in #281 to test it. However, @mmann1123 let us know if you can pin `numpy` to `>=1.19.0` in the `conda` build.

**Comment by mmann1123** [comment]
@jgrss Looks like pinning 1.19 to conda will work fine.  I just pushed the changes. I think we can close this. 
https://github.com/conda-forge/geowombat-feedstock/pull/103

**Comment by jgrss** [comment]
@DManowitz I am going to close this but please reopen if the problem persists.
