### ISSUE TITLE
Regression capability in geowombat

### ISSUE THREAD

**Issue by ritviksahajpal** [jgrss/geowombat#284]
Thanks for a great package! Are you planning to include the capability to use geowombat for solving regression tasks?

thanks!
Ritvik

**Comment by jgrss** [comment]
Hi @ritviksahajpal, thanks for the question. Are you referring to the `ml` module? Currently, there are no plans to add regression. However, we (@mmann1123) would be happy to look into it if there is interest. Do you have a specific idea or example in mind, or basically a general framework similar to the [classifiers module](https://github.com/jgrss/geowombat/blob/main/src/geowombat/ml/classifiers.py)?
