### ISSUE TITLE
GDAL_DATA

### ISSUE THREAD

**Issue by mmann1123** [jgrss/geowombat#29]
I started a new conda env and once again have GDAL path issues. I noticed that fiona seems to have resolved this internally, and thinking maybe we could implement their solution, see link below. Wish I could be of help on this, but this is way above my pay grade. 
 
CPLE_OpenFailedError: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.

[Link to related fiona issue](https://github.com/Toblerity/Fiona/issues/673#issuecomment-444046688)

**Comment by jgrss** [comment]
It looks like [this issue](https://github.com/jgrss/geowombat/issues/23). Perhaps we need to add an example of how to set the `GDAL_DATA` variable to the installation page.

**Comment by jgrss** [comment]
@mmann1123 I installed GDAL 3.0.2 on Ubuntu and configured my GDAL environment as:

export CPLUS_INCLUDE_PATH=/usr/include/gdal
export C_INCLUDE_PATH=/usr/include/gdal
export GDAL_DATA=../envs/ts3.7/lib/python3.7/site-packages/fiona/gdal_data

**Comment by jgrss** [comment]
Which version of GDAL are you using? The normal `GDAL_DATA` directory (i.e., /usr/share/gdal/) for 3.0.2 was missing some files.

**Comment by mmann1123** [comment]
Yeah I realized that the lookup tables were missing for 302 the other day.
What a pain in my butt, but easy fix.

**Comment by jgrss** [comment]
Closing this since it is now in the [documentation](https://geowombat.readthedocs.io/en/latest/install.html#gdal-install-ubuntu).
