### ISSUE TITLE
EVI equation is wrong

### ISSUE THREAD

**Issue by christophfriedrich** [jgrss/geowombat#293]
I was calculating the EVI with your library and didn't get the results I was expecting, so I had a closer look at the docs and found the equation listed [there](https://geowombat.readthedocs.io/en/latest/api/geowombat.core.geoxarray.GeoWombatAccessor.html#geowombat.core.geoxarray.GeoWombatAccessor.evi) to be:

![image](https://github.com/jgrss/geowombat/assets/17781682/f85c6a0b-a973-4cdd-b632-b668f29c5259)

At first I thought the first times-sign in the denominator was a typo in the docs, but the respective code indeed is:

https://github.com/jgrss/geowombat/blob/6c8b96bb2c3ed772ff9843a95a87a94ae0a35d5d/src/geowombat/core/vi.py#L354-L365

That `*` on line 360 should be a `+`.

References: [Index Database](https://www.indexdatabase.de/db/i-single.php?id=16), [USGS](https://www.usgs.gov/landsat-missions/landsat-enhanced-vegetation-index), [Huete et al 2002](https://www.sciencedirect.com/science/article/pii/S0034425702000962#BIB39)

**Comment by jgrss** [comment]
HI @christophfriedrich, thanks for raising this. See #294 for the fix.

**Comment by christophfriedrich** [comment]
Thank you for taking care of this so quickly, Friday afternoon to Tuesday morning is quite a nice time from first report to released fix! 👍 I tried it straight away and am now getting the same results as manually in QGIS 👌

Except for areas of very high or low values, as Geowombat clamps the value range to [0,1]. You might want to consider removing this behaviour or at least provide an option to disable it? Unlike NDVI, which is always in [-1,1], values outside [0,1] are absolutely possible and normal for EVI (see e.g. [here](https://gis.stackexchange.com/a/227168)).

Also, you might want to update the examples in your documentation, e.g. in the [Band Math section](https://geowombat.readthedocs.io/en/latest/band-math.html), as now the `scale_factor` isn't necessary anymore (it corrected the unintended multiplication of the two four-digit numbers in the denominator which made the result super small).
