### ISSUE TITLE
Allow both subset using window and stack_dim

### ISSUE THREAD

**Issue by rdenham** [jgrss/geowombat#33]
Just wondering if it would be possible to allow both opening multiple images using `stack_dim` and at the same time subsetting using `window`. 

Here's what I'd like to do:

```python
import geowombat as gw
from rasterio.windows import Window

w = Window(row_off=0, col_off=0, height=100, width=100)

with gw.open([rgbn, rgbn],
             band_names=['b1', 'g1', 'r1', 'n1', 'b2', 'g2', 'r2', 'n2'],
             stack_dim='band',
             window = w) as ds:
   print(ds)
```
gives an error "The band names do not match the output dimensions." Checking the error, it seems that the data shape is (2, 4, 100, 100). So,

```python
with gw.open([rgbn, rgbn],
             band_names=['b', 'g', 'r', 'n'],
             time_names = ['old', 'new'],
             window = w) as ds:
   print(ds)
```
works fine. 

I'm using `geowombat version 1.2.9`

**Comment by jgrss** [comment]
The `window` argument in `geowombat.open` triggers `dask.delayed` reads, which might be faster than using `xarray.open_rasterio` when opening multiple files. However, it currently has some limited functionality when it comes to multiple band images.

I would recommend using the `geowombat.config.update` manager in most I/O cases. As of version `1.2.9`, `geowombat.config.update` accepts `ref_bounds` as an image or a tuple of (left, bottom, right, top). I am adding support to pass `rasterio.windows.Window` and `rasterio.coords.BoundingBox` objects as well. With the upcoming changes, you can do:

```python
import geowombat as gw
from geowombat.data import rgbn
from rasterio.windows import Window

w = Window(row_off=0, col_off=0, height=100, width=100)

with gw.config.update(ref_bounds=w):
    with gw.open([rgbn, rgbn],
                      band_names=['b1', 'g1', 'r1', 'n1', 'b2', 'g2', 'r2', 'n2'],
                      stack_dim='band') as src:
        print(src)
```

Just note that if you use a window, GeoWombat expects all of the images to be aligned. If they are not aligned, use coordinates like:

```python
bounds = (left, right, bottom, top)

with gw.config.update(ref_bounds=bounds):
    with gw.open([rgbn, rgbn],
                      band_names=['b1', 'g1', 'r1', 'n1', 'b2', 'g2', 'r2', 'n2'],
                      stack_dim='band') as src:
        print(src)
```

or

```python
from rasterio.coords import BoundingBox

bounds = BoundingBox(left=left, bottom=bottom, right=right, top=top)

with gw.config.update(ref_bounds=bounds):
    with gw.open([rgbn, rgbn],
                      band_names=['b1', 'g1', 'r1', 'n1', 'b2', 'g2', 'r2', 'n2'],
                      stack_dim='band') as src:
        print(src)
```

**Comment by jgrss** [comment]
Test the example above in version `1.2.10`.
