### ISSUE TITLE
Adding sklearn compatability

### ISSUE THREAD

**Issue by mmann1123** [jgrss/geowombat#44]
I opened an issue with sklearn-xarray folks about [integration with geowombat data structures](https://github.com/phausamann/sklearn-xarray/issues/52). They answered with a working example and I simultaneously figured most of it out and created a pull request to make it easier for us to use. 

[](https://github.com/phausamann/sklearn-xarray/issues/52)

They want to create an example using gw data but worried most folks will have trouble generating the environment. I hate to ask you for something, but they are hoping for a dummy data set with some randomly created data to use as an example. I honestly have tried a few times and for many hours (and failed) to generate the same structure as:

``
with gw.open([rgbn_20160101, rgbn_20160401, rgbn_20160517],
                 band_names=['blue', 'green', 'red','nir'],
                 time_names=['t1', 't2','t3']) as src:
src
```
Any chance you know how to recreate that easily using xarray only?  Might be useful for testing later anyways.

**Comment by jgrss** [comment]
@mmann1123 here is an example of how you might setup some random data without using geowombat. 

## Exclusive of geowombat

```python
import numpy as np
import dask.array as da
import xarray as xr
```

## Create a random dask array

```python
nrows = 100
ncols = 200
row_chunks = 50
col_chunks = 50

data = da.random.random(size=(1, nrows, ncols), chunks=(1, row_chunks, col_chunks))
```

## Data creation functions

```python
def create_band(data, x, y, band_name):

    return xr.DataArray(data,
                        dims=('band', 'y', 'x'),
                        coords={'band': [band_name],
                                'y': y,
                                'x': x})
```

```python
def create_coords(data, left, top, celly, cellx):
    nrows = data.shape[-2]
    ncols = data.shape[-1]
    right = left + cellx*ncols
    bottom = top - celly*nrows
    x = np.linspace(left, right, ncols) + cellx/2.0
    y = np.linspace(top, bottom, nrows) - celly/2.0
    
    return x, y
```

## Create the coordinates

```python
x, y = create_coords(data, 1000, 2000, 30, 30)
```

## Create the `DataArray`

```python
src = []

for time in ['t1', 't2', 't3']:

    src_t = xr.concat([create_band(data, x, y, band) for band in ['blue', 'green', 'red', 'nir']], dim='band')\
                    .expand_dims(dim='time')\
                    .assign_coords({'time': [time]})
    
    src.append(src_t)

src = xr.concat(src, dim='time')
```

```python
print(src)

<xarray.DataArray 'random_sample-863424ab3697a58ff124ec5f1e288970' (time: 3, band: 4, y: 100, x: 200)>
dask.array<concatenate, shape=(3, 4, 100, 200), dtype=float64, chunksize=(1, 1, 100, 200), chunktype=numpy.ndarray>
Coordinates:
  * band     (band) object 'blue' 'green' 'red' 'nir'
  * y        (y) float64 1.985e+03 1.955e+03 1.924e+03 ... -984.7 -1.015e+03
  * x        (x) float64 1.015e+03 1.045e+03 1.075e+03 ... 6.985e+03 7.015e+03
  * time     (time) object 't1' 't2' 't3'

```

**Comment by phausamann** [comment]
Hi @jgrss, I'm the author of sklearn-xarray and have been discussing an example of land use classification with @mmann1123. 

Ideally I'd like to use a dataset that includes both actual satellite images and ground truth labels for the land use as this would make for a nice visual example. I've found datasets like [this one](https://ldas.gsfc.nasa.gov/nldas/vegetation-class) with labeled land cover but haven't been able to find the underlying satellite images. 

At a quick glance, it doesn't seem like the example data that comes with geowombat provides this, only the raw satellite images. If you where I could find such a dataset that would be very helpful, although I know that this issue isn't really related to the geowombat package itself.

**Comment by jgrss** [comment]
Hi @phausamann, It won't be a problem to put some data together. I can prepare something from [MAPBIOMAS](https://mapbiomas.org/en/download?cama_set_language=en) or the [USGS NLCD](https://www.usgs.gov/centers/eros/science/national-land-cover-database?qt-science_center_objects=0#qt-science_center_objects). I think that @mmann1123 and I would like to have a `predict()` method in geowombat (which will likely wrap around your library), so some land cover test data will be useful for us anyway.

We do, however, have some vector example data. The data are not great for a full image example because they are pretty limited and really only there to show the utility of the `extract()` function. Nevertheless, the example below demonstrates a geowombat/xarray/dask fit/predict example with ground truth data. 

```python
import geowombat as gw
from geowombat.core import dask_to_xarray
from geowombat.data import l8_224078_20200518, l8_224078_20200518_polygons

from sklearn import ensemble
from dask_ml.wrappers import ParallelPostFit

clf_ = ensemble.RandomForestClassifier(n_estimators=50, max_depth=25, n_jobs=8)

# Declare the satellite as blue, green, red
with gw.config.update(sensor='bgr'):
    
    # blue, green, red composite of Landsat 8 data
    with gw.open(l8_224078_20200518) as src:

        # Extract values within the land cover polygons
        df = src.gw.extract(l8_224078_20200518_polygons,
                                      band_names=src.band.values.tolist())
        
        X = df[src.band.values.tolist()].values
        y = df['poly'].values
        
        # Fit a RF classifier
        clf_.fit(X, y)
        clf = ParallelPostFit(estimator=clf_)
        
        pred = clf.predict(src.stack(z=('y', 'x'))\
                        .transpose()\
                        .chunk(src.gw.row_chunks*src.gw.col_chunks, src.gw.nbands).data)\
                    .reshape(src.gw.nrows, src.gw.ncols)\
                             .rechunk(src.gw.row_chunks, src.gw.col_chunks)
        
        # Convert the dask array to a DataArray
        pred = dask_to_xarray(src, pred, ['lc'])
        
        print(pred)
        
        pred.sel(band='lc').plot.imshow()
```

which prints

```python
<xarray.DataArray 'reshape-7a2d8478dce45399e7119f28982192c7' (band: 1, y: 1860, x: 2041)>
dask.array<reshape, shape=(1, 1860, 2041), dtype=int64, chunksize=(1, 256, 256), chunktype=numpy.ndarray>
Coordinates:
  * band     (band) <U2 'lc'
  * y        (y) float64 -2.777e+06 -2.777e+06 ... -2.833e+06 -2.833e+06
  * x        (x) float64 7.174e+05 7.174e+05 7.174e+05 ... 7.785e+05 7.786e+05
Attributes:
    transform:      (30.0, 0.0, 717345.0, 0.0, -30.0, -2776995.0)
    crs:            +init=epsg:32621
    res:            (30.0, 30.0)
    is_tiled:       1
    nodatavals:     (nan, nan, nan)
    scales:         (1.0, 1.0, 1.0)
    offsets:        (0.0, 0.0, 0.0)
    AREA_OR_POINT:  Area
    sensor:         blue, green, and red
    resampling:     nearest
```

![lc](https://user-images.githubusercontent.com/6633570/89891177-f1f5d580-dc17-11ea-8c49-392f604f9ee3.png)

**Comment by mmann1123** [comment]
I will be curious what @phausamann thinks we should do, but @jgrss it seems like we can tie sk-xr in, just need to have some transformers for common gw data structures (see Featurizer, and Stackerizer https://github.com/mmann1123/sklearn-xarray/blob/patch-1/sklearn_xarray/preprocessing.py). It might be easier to keep an equivalent of extract that returns a xarray that is groupby mean for each polygon and then stacked by (x,y, time), that way we could predict directly back to the gw object.

**Comment by jgrss** [comment]
@mmann1123 I was thinking that the `geowombat.predict` method might look something like:

```python
# fit a model (this could be sklearn, sklearn-xarray, lightgbm, etc.)
clf.fit(X, y)

# predict on an image with matching features to X
with gw.open('image.tif') as src:
    # Predict returns a DataArray
    pred = gw.predict(src, clf)
    pred.gw.to_raster('map.tif')
```

where `gw.predict` would just transform the data and apply the classifier.

What do you think?

**Comment by jgrss** [comment]
In regards to returning a `DataArray` with `gw.extract` -- I think I would need to see an example of the structure. I usually work with point (x, y) data or polygon data, but rarely with other land use/cover maps.

**Comment by phausamann** [comment]
Thanks @jgrss, that example is very helpful and exactly what I'm looking for. If I understand correctly, the ground truth data is available as polygons and then gets "interpolated" at the pixel locations by predicting with the fitted estimator?

In any case, with:
```
src.coords["land_cover"] = pred.drop("band").squeeze()
```
`src` could be directly used in an sklearn-xarray workflow.

**Comment by phausamann** [comment]
Regarding integration with the package, I'm not really familiar with gw workflows, but I'd be happy help if any issues come up.

**Comment by jgrss** [comment]
@phausamann 

> If I understand correctly, the ground truth data is available as polygons and then gets "interpolated" at the pixel locations by predicting with the fitted estimator?

Yes, in the `gw.extract` function, the values at each pixel within the polygons are stored into a `DataFrame` and used to fit the classifier. In the example above, there are only 4 polygons, but `df` has 672 rows by taking the 672 (30m x 30m) pixels within the 4 polygons. 

We typically have land use/cover data collected from the field via GPS and/or digitized polygons interpreted from high-resolution imagery. So, I would like to be able to fit classifiers to DataFrames similar to the one above and easily apply the classifier to a `DataArray` with the same coordinate names as the `DataFrame` column names. It looks like `sklearn-xarray` solves this nicely. I think as we design this module in geowombat, we might be reaching out to you further. As @mmann1123 said, we probably just need to handle the data reshaping and renaming since you've done the machine learning part. I need to familiarize myself more with your library, though.

**Comment by jgrss** [comment]
@mmann1123 Have you used `gw.extract` on your multi-temporal data? 

```python
with gw.config.update(sensor='bgr'):
    
    with gw.open([l8_224078_20200518, l8_224078_20200518], 
                     time_names=['t1', 't2'],
                     stack_dim='time') as src:

        df = src.gw.extract(l8_224078_20200518_polygons,
                            band_names=src.band.values.tolist())
````

The output columns will look like...

```text
t1_blue | t1_green | t1_red | t2_blue | t2_green | t2_red
```

**Comment by mmann1123** [comment]
Hey jordan, I will try to send some examples of the xr structures we are looking for today. 

The primary issue I have with extract is that I am doing longitudinal data structures (long not wide) 

I would normally flatten these array using a multi-index as follows and store them as a pd.dataframe:

| Pixel  | Time | Target |  R |  G | ....|
| -- | -- | --|---| -- | -- |
| 1 | T1  |Forest| 50 | 230  | .... |
| 1 | T2  |Agriculture| 180| 30 | .... |
| 2 | T1  |Water| 43| 55 | .... |
| 2 | T2  |Water| 50| 66 | .... |

I think there are a lot of advantages to keeping the data in xarray (even if this is based on extracting from point or polygon) because the workflow from preprocessing to predicting becomes seamless regardless of the type of data in gw.  

I will try to put together an example in a bit.

**Comment by mmann1123** [comment]
Ok so how nice is this. 

### Starting with your random data example above:
```
<xarray.DataArray 'random_sample-a19895ecc83ce43974cb069a42d58a48' (time: 3, band: 4, y: 100, x: 200)>
dask.array<concatenate, shape=(3, 4, 100, 200), dtype=float64, chunksize=(1, 1, 50, 50), chunktype=numpy.ndarray>
Coordinates:
  * band     (band) object 'blue' 'green' 'red' 'nir'
  * y        (y) float64 1.985e+03 1.955e+03 1.924e+03 ... -984.7 -1.015e+03
  * x        (x) float64 1.015e+03 1.045e+03 1.075e+03 ... 6.985e+03 7.015e+03
  * time     (time) object 't1' 't2' 't3'
```
### Create target data 
``` python
land_use = np.tile( "water", (src.sizes["time"], src.sizes["y"], src.sizes["x"]) ).astype(object)
land_use[src.sel(band='green').values > 0.5] = "forest"
land_use = land_use.astype(str)
src.coords["land_use"] = (["time", "y", "x"], land_use)

X = Stackerizer(stack_dims = ('x','y','time'), direction='stack').fit_transform(src)

print(X)
print('----------------------')
print(X.values)
print(X.land_use.values)

print('----------------------')
print(X.shape)
print(X.land_use.shape)
```
```
<xarray.DataArray 'random_sample-a19895ecc83ce43974cb069a42d58a48' (sample: 60000, band: 4)>
dask.array<transpose, shape=(60000, 4), dtype=float64, chunksize=(3000, 1), chunktype=numpy.ndarray>
Coordinates:
  * band      (band) object 'blue' 'green' 'red' 'nir'
    land_use  (sample) <U6 'water' 'water' 'water' ... 'water' 'water' 'water'
  * sample    (sample) MultiIndex
  - x         (sample) float64 1.015e+03 1.015e+03 ... 7.015e+03 7.015e+03
  - y         (sample) float64 1.985e+03 1.985e+03 ... -1.015e+03 -1.015e+03
  - time      (sample) object 't1' 't2' 't3' 't1' 't2' ... 't3' 't1' 't2' 't3'
----------------------
[[0.27828509 0.27828509 0.27828509 0.27828509]
 [0.27828509 0.27828509 0.27828509 0.27828509]
 [0.27828509 0.27828509 0.27828509 0.27828509]
 ...
 [0.14799641 0.14799641 0.14799641 0.14799641]
 [0.14799641 0.14799641 0.14799641 0.14799641]
 [0.14799641 0.14799641 0.14799641 0.14799641]]
['water' 'water' 'water' ... 'water' 'water' 'water']
----------------------
(60000, 4)
(60000,)
```
### Send to ML pipeline
``` python
pl = Pipeline(
    [  
       ("sanitizer", Sanitizer()),    # Remove elements containing NaNs.
       ("featurizer", Featurizer()),  # Stack all dimensions and variables except for sample dimension.
       ("scaler", wrap(StandardScaler)), # zscores , ?wrap if xarray.self required? 
       ("pca", wrap(PCA, reshapes="feature")), 
       ("cls", wrap(GaussianNB, reshapes="feature")),
    ]
)

##############################################################################
# Since we want to use cross-validated grid search to find the best model
# parameters, we define a cross-validator. In order to make sure the model
# performs subject-independent recognition, we use a `GroupShuffleSplit`
# cross-validator that ensures that the same subject will not appear in both
# training and validation set.

cv = CrossValidatorWrapper(
    GroupShuffleSplit(n_splits=3, test_size=0.5), groupby=["time"]
)

##############################################################################
# The grid search will try different numbers of PCA components to find the best
# parameters for this task.

gs = GridSearchCV(
    pl, cv=cv, n_jobs=-1, verbose=1, param_grid={"pca__n_components": [5,10]}
)

##############################################################################
# The label to classify is the activity which we convert to an integer
# representation for the classification.

y = Target(
    coord="land_use", transform_func=LabelEncoder().fit_transform )(X)

gs.fit(X, y)
print("Best parameters: {0}".format(gs.best_params_))
print("Accuracy: {0}".format(gs.best_score_))
```
```
Fitting 3 folds for each of 2 candidates, totalling 6 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=-1)]: Done   4 out of   6 | elapsed:    4.6s remaining:    2.3s
[Parallel(n_jobs=-1)]: Done   6 out of   6 | elapsed:    4.8s finished

Best parameters: {'pca__n_components': 5}
Accuracy: 0.99965
```
### Predict back to stack
``` python 
yp = gs.predict(X)
yp.values = LabelEncoder().fit(X.land_use).classes_[yp]
yp = yp.unstack("sample")
print(yp)
```
```
<xarray.DataArray (x: 200, y: 100, time: 3)>
array([[['water', 'water', 'water'],
        ['water', 'water', 'water'],
        ['forest', 'forest', 'forest'],
        ...,
        ['forest', 'forest', 'forest'],
        ['forest', 'forest', 'forest'],
        ['water', 'water', 'water']]], dtype='<U6')
Coordinates:
    land_use  (x, y, time) <U6 'water' 'water' 'water' ... 'water' 'water'
  * x         (x) float64 1.015e+03 1.045e+03 1.075e+03 ... 6.985e+03 7.015e+03
  * y         (y) float64 1.985e+03 1.955e+03 1.924e+03 ... -984.7 -1.015e+03
  * time      (time) object 't1' 't2' 't3'
```

**Comment by jgrss** [comment]
@mmann1123 this looks great.

In your example where you generate fake labels

```python
land_use = np.tile( "water", (src.sizes["time"], src.sizes["y"], src.sizes["x"]) ).astype(object)
land_use[src.sel(band='green').values > 0.5] = "forest"
land_use = land_use.astype(str)
src.coords["land_use"] = (["time", "y", "x"], land_use)
```

What happens when you don't have labels for every pixel in the raster? How does `sklearn xarray` treat nulls?

For example, say instead of wall-to-wall labels, you had polygons that you wanted to sample for each time period.

```python
import geowombat as gw
from geowombat.data import l8_224078_20200518_polygons,

# Using the fake, random data, so assigning fake attributes
src = src.assign_attrs(crs='epsg:4326', res=(30, 30))

# Convert the polygon data to a DataArray
poly_array = gw.polygon_to_array(l8_224078_20200518_polygons, data=src, src_res=src)

# Assuming your training data are the same for each time period
poly_array = xr.concat([poly_array]*src.gw.ntime, dim='band').assign_coords({'band': src.time.values.tolist()})

# Set non-existing data as nans
poly_array = poly_array.where(poly_array != 0)

# Store the training data
src.coords['land_use'] = (["time", "y", "x"], poly_array)
```

```python
print(poly_array)

<xarray.DataArray 'zeros-ee4df5ccdcb08e40e876d6f2da070b0e' (band: 3, y: 100, x: 200)>
dask.array<where, shape=(3, 100, 200), dtype=float64, chunksize=(1, 50, 50), chunktype=numpy.ndarray>
Coordinates:
  * x        (x) float64 1.015e+03 1.045e+03 1.075e+03 ... 6.985e+03 7.015e+03
  * y        (y) float64 1.985e+03 1.955e+03 1.924e+03 ... -984.7 -1.015e+03
  * band     (band) <U2 't1' 't2' 't3'
Attributes:
    crs:      epsg:4326
    res:      (30, 30)
```

```python
print(src)

<xarray.DataArray 'random_sample-51ce68a4a8f18f9a42888afd4b7aecde' (time: 3, band: 4, y: 100, x: 200)>
dask.array<concatenate, shape=(3, 4, 100, 200), dtype=float64, chunksize=(1, 1, 50, 50), chunktype=numpy.ndarray>
Coordinates:
  * y         (y) float64 1.985e+03 1.955e+03 1.924e+03 ... -984.7 -1.015e+03
  * band      (band) object 'blue' 'green' 'red' 'nir'
  * x         (x) float64 1.015e+03 1.045e+03 1.075e+03 ... 6.985e+03 7.015e+03
  * time      (time) object 't1' 't2' 't3'
    land_use  (time, y, x) float64 nan nan nan nan nan ... nan nan nan nan nan
Attributes:
    crs:      epsg:4326
    res:      (30, 30)
```

**Comment by jgrss** [comment]
The `polygon_to_array` example above returns all nulls because the fake CRS and coordinates don't align with the polygons. It looks like I need to fix an issue with `polygon_to_array` with multiple raster files, but here is an example of the conversion.

```python
with gw.open(l8_224078_20200518, chunks=50) as src:
    
    poly_array = gw.polygon_to_array(l8_224078_20200518_polygons, data=src, src_res=src)
    poly_array.sel(band=1).gw.imshow()
```

**Comment by jgrss** [comment]
Alright, with geowombat==1.2.28, the following now works

```python
with gw.open([l8_224078_20200518, l8_224078_20200518, l8_224078_20200518], time_names=['t1', 't2', 't3'], stack_dim='time', chunks=50) as src:
    
    poly_array = gw.polygon_to_array(l8_224078_20200518_polygons, data=src)
    poly_array = xr.concat([poly_array]*src.gw.ntime, dim='band').assign_coords({'band': src.time.values.tolist()})
    poly_array = poly_array.where(poly_array != 0)
    src.coords['land_use'] = (["time", "y", "x"], poly_array)
```

**Comment by mmann1123** [comment]
@jgrss  Made some progress. Have a basic working version

Notice I am using the new rasterizer version for PR above. 

```python
# adding observations so we can play with repeated classes

poly = gpd.read_file(l8_224078_20200518_polygons)
poly2 = poly.copy()
poly2.geometry = poly.buffer(100)
poly2 =gpd.overlay(poly2,poly, how='difference')
polygons = poly.append(poly2)
polygons.reset_index(inplace=True, drop =True)
polygons

# create numeric labels 
polygons['id'] = range(len(polygons))
le = LabelEncoder()
polygons['lu'] = le.fit(polygons.name).transform(polygons.name)
polygons

with gw.open([l8_224078_20200518, l8_224078_20200518, l8_224078_20200518], time_names=['t1', 't2', 't3'], stack_dim='time', chunks=50) as src:
    
    poly_array = gw.polygon_to_array(polygons, col='id', data=src )
    print(np.unique(poly_array.sel(band=1).values))
    poly_array = xr.concat([poly_array]*src.gw.ntime, dim='band').assign_coords({'band': src.time.values.tolist()})
    poly_array = poly_array.where(poly_array != 0)
    src.coords['land_use'] = (["time", "y", "x"], poly_array)
    print(src)

X = Stackerizer(stack_dims = ('y','x','time'), direction='stack').fit_transform(src)   # NOTE stack y before x!!! 
X

#drop nans from landuse
Xna = X[~X.land_use.isnull()]
Xna

# haven't figured out the group by yet but just in case heres the start
Xgp = Xna.groupby('land_use').mean('sample')
Xgp

pl = Pipeline(
    [  
       ("featurizer", Featurizer()),  # Stack all dimensions and variables except for sample dimension.
       ("scaler", wrap(StandardScaler)), # zscores , ?wrap if xarray.self required? 
        ("pca", wrap(PCA, reshapes="feature")), 
       ("cls", wrap(GaussianNB, reshapes="feature")),
    ]
)

cv = CrossValidatorWrapper(
    GroupShuffleSplit(n_splits=1, test_size=0.5), groupby=["time"]
)

gs = GridSearchCV(
    pl, cv=cv,   verbose=1, param_grid={"pca__n_components": [5]}
)

y = Target(
    coord="land_use", transform_func=LabelEncoder().fit_transform,dim="sample" )(Xna)

gs.fit(Xna, y) 
print("Accuracy: {0}".format(gs.best_score_))

# predict 
yp = gs.predict(X)
yp = yp.unstack("sample")
yp.sel(time='t1').plot.imshow()

```

**Comment by jgrss** [comment]
@mmann1123 I was originally thinking that we would just have a `predict` method and leave all of the fitting to `sklearn-xarray`. However, in your example, the prediction is just

```python
yp = gs.predict(X).unstack('sample')
yp.gw.to_raster(...)
```

so we wouldn't really need a `gw.predict`.

Do we want a helper function for the model fitting, or leave it to the user? It might be nice to to have a `fit` method that handles geospatial data. For example, something like

```python
with gw.open([l8_224078_20200518, l8_224078_20200518, l8_224078_20200518], time_names=['t1', 't2', 't3'], stack_dim='time', chunks=50) as src:
    # The polygons could be a file name or a GeoDataFrame
    X, clf = gw.fit(src, l8_224078_20200518_polygons)
    yp = clf.predict(X).unstack('sample')
    # or
    # yp = gw.fit_predict(src, l8_224078_20200518_polygons)
```

where the `fit` method would handle all of the things you did in the example above.

**Comment by mmann1123** [comment]
Yeah I think something that handles the transformations would be a decent
idea, certainly would make things more approachable.

**Comment by jgrss** [comment]
@mmann1123 I started a skeleton for the machine learning module. See the `geowombat.ml` module in the [the ml branch](https://github.com/jgrss/geowombat/tree/ml).

**Comment by mmann1123** [comment]
I think a stacker function will be available on sk-xr (@phausamann) soon (on [PR](https://github.com/phausamann/sklearn-xarray/blob/3ed1fc33adecbcb0cc54c4da5041bfd36d446279/sklearn_xarray/preprocessing.py)).

In the meantime do you want to copy a version from [xr_fresh](https://github.com/mmann1123/xr_fresh/blob/master/xr_fresh/transformers.py)?

@jgrss

**Comment by jgrss** [comment]
@mmann1123 I merged your addition of the transformers. Let's replace it with `sklearn-xarray` when they've pushed a new release.

**Comment by mmann1123** [comment]
(moving comment from PR) I was working on figuring out the single date issue with predict. I didn't make much progress other than finding a work around. Maybe we can just always construct a 1 length time dim.

The following works:

with gw.open( [l8_224078_20200518], chunks=50) as src:    
    src = src.assign_coords(time=1)

    y = fit_predict(src, labels = polygons, col = 'id', grid_search =False,
                            targ_dim_name='sample', clf=clf,targ_name = 'land_use')

y[:,:,0].plot.imshow()

**Comment by jgrss** [comment]
@mmann1123 I added the check for the 'time' coordinate [here](https://github.com/jgrss/geowombat/commit/8cea530d128cee8c9e7658bfde72da77a9cff312).

**Comment by jgrss** [comment]
@mmann1123 I haven't had time to debug the `ml.fit` method. It wasn't working for me, although I thought I reproduced your example. If you have time, could you test it?

**Comment by jgrss** [comment]
@mmann1123 The latest version of the [ml branch](https://github.com/jgrss/geowombat/tree/ml) has a working `fit` and `fit_predict` method when using a `Pipeline`. It still isn't working with a single classifier, though.

I changed a few things:
- Fixed the check for the time coordinate
- Allowed use of all sklearn models (they are checked and sklearn-xarray-wrapped, if necessary)
- Changed the output of the `fit_predict` to a reshaped `DataArray` of time x band x rows x columns

See the examples in the docstrings of `ml.fit` and `ml.fit_predict` for details.

**Comment by mmann1123** [comment]
Ok yeah looks good, sorry I didn't get time for fixing that! I just pushed some minor doc edits.

**Comment by jgrss** [comment]
@mmann1123 I've merged `ml` with `master` locally and I am adding some documentation examples. After I tidy up a bit, I will push `1.3.0`, which will include the `ml` module.

**Comment by jgrss** [comment]
@mmann1123 I pushed changes in version `1.3.0`. See the [changelog](https://geowombat.readthedocs.io/en/latest/changelog.html) for details. I added an [example page](https://geowombat.readthedocs.io/en/latest/ml.html), but feel free to add more detail.

**Comment by phausamann** [comment]
There's a `Stacker` transformer on the sklearn-xarray develop branch now. However, I'd like to add the land cover classification example before making a new minor release.

Here's what the example data should ideally look like:
```
<xarray.DataArray (band: 3, y: 1860, x: 2041)>
array([[[   0,    0,    0, ...,    0,    0,    0],
        [   0,    0,    0, ...,    0,    0,    0],
        [   0,    0,    0, ...,    0,    0,    0],
        ...,
        [7692, 7518, 7513, ..., 7440, 7432, 7415],
        [7586, 7590, 7610, ..., 7440, 7411, 7425],
        [7576, 7743, 7770, ..., 7464, 7443, 7406]],
       [[   0,    0,    0, ...,    0,    0,    0],
        [   0,    0,    0, ...,    0,    0,    0],
        [   0,    0,    0, ...,    0,    0,    0],
        ...,
        [7083, 6794, 6731, ..., 6760, 6724, 6685],
        [6951, 7079, 7016, ..., 6699, 6687, 6715],
        [6864, 7286, 7338, ..., 6817, 6732, 6659]],
       [[   0,    0,    0, ...,    0,    0,    0],
        [   0,    0,    0, ...,    0,    0,    0],
        [   0,    0,    0, ...,    0,    0,    0],
        ...,
        [6672, 6168, 6100, ..., 6028, 6015, 6008],
        [6291, 6457, 6423, ..., 6021, 6001, 6017],
        [6181, 6727, 6747, ..., 6098, 6023, 5991]]], dtype=uint16)
Coordinates:
  * band        (band) <U5 'blue' 'green' 'red'
  * y           (y) float64 -2.777e+06 -2.777e+06 ... -2.833e+06 -2.833e+06
  * x           (x) float64 7.174e+05 7.174e+05 ... 7.785e+05 7.786e+05
    land_cover  (y, x) int64 2 2 2 2 2 2 2 2 2 2 2 2 ... 2 2 2 2 2 2 2 2 2 2 2 2
```

although `land_cover` should be in string format ("Forest", "Water", etc.) instead of int.

The easiest way would be to add this data to the package as a netCDF4 file. It might also be useful to have multiple images with ground truth annotations, to split into a training and a test set.

Also, I've had difficulties plotting the image with imshow. I've tried dividing by 2**16, but I get a very dark, low contrast image. I'm assuming this has something to do with the higher dynamic range of the satellite data. Still, it would be nice to plot the image in the example.

**Comment by mmann1123** [comment]
@phausamann I just posted a link to an example dataset similar to what you are looking for. Only main difference is that there are very few landcover training values (most are NaN) which is very typical of this type of work. Let me know if that does the trick. 

 [dropbox link](https://www.dropbox.com/s/ktnhv9skc1esbr2/example.nc?dl=0)

**Comment by mmann1123** [comment]
Found one issue for my use case. If the array is large (many pixels, dates, bands), stacking by (y,x,time) is problematic. I am playing around with some possible solutions now. I will keep you updated if I come up with a solution. @phausamann @jgrss

**Comment by mmann1123** [comment]
Ok I have a potential solution, need to try it at scale. Ideally we could write to disk as we go, but this might minimize overhead enough to calculate on larger data. 
```python 

def user_func(*args):

    """
    Block-level function to be executed in parallel. The first argument is the block data, and
    the second argument is the number of parallel worker threads for dask.compute().
    """

    # Gather function arguments
    data, num_workers = list(itertools.chain(*args))

    # Send the computation to Dask
    print(data.data.shape)
    return data.stack(sample=('y','x','time')).T.compute(scheduler='threads', num_workers=num_workers)
   

with gw.open([l8_224078_20200518, l8_224078_20200518, l8_224078_20200518], time_names=[1, 2, 3], stack_dim='time', chunks=50) as src:
    
    #poly_array = gw.polygon_to_array(polygons, col='id', data=src )
    #print(np.unique(poly_array.sel(band=1).values))
    #poly_array = xr.concat([poly_array]*src.gw.ntime, dim='band').assign_coords({'band': src.time.values.tolist()})
    #poly_array = poly_array.where(poly_array != 0)
    #src.coords['land_use'] = (["time", "y", "x"], poly_array)
    src = src.chunk({'time': -1, 'band':1, 'y':800,'x':800})  # rechunk to time 

    pt = ParallelTask(src,
                        scheduler='threads',
                        n_workers=8)
    res = pt.map(user_func, 1)            
    out = xr.combine_nested(res, concat_dim = ['sample', ])    
```
@phausamann @jgrss

**Comment by jgrss** [comment]
@mmann1123 How did this work at scale?

**Comment by mmann1123** [comment]
Honestly, I am hung up on at the moment. Seems like in most cases we will need to chunk up the data and store it to disk after the `stack`.  Since `sample` is a multiindex HDF files won't work natively (I have a zombie [stackoverflow question](https://stackoverflow.com/questions/63906769/writing-xarray-multiindex-data-in-chunks) wait wait waiting for a response about this).  For the moment I have been trying to use parquet files, since they can handle multi-index and work with dask.  Although I haven't given up yet, it isn't working as well as I hoped. 


``` python

def user_func(*args):
 
    data, num_workers = list(itertools.chain(*args))

    timer = int(round(time.time() * 1000))
    X = data.stack(sample=('y','x','time')).T.compute(scheduler='threads', num_workers=num_workers)

    X = X.to_pandas() 
    X.columns = X.columns.astype(str)
    X.to_parquet(out_folder+'/stacked_data_Xy_parts/NDVI_2010-2016_Xy_croploss_'+ \
                                os.path.splitext(block)[0]+'_%04d.parquet' %  timer)
 
    return None
```

**Comment by jgrss** [comment]
Hi @mmann1123 

Did you solve this with `dask.store`? Thinking we can close this issue.

**Comment by mmann1123** [comment]
yes that worked nicely. thanks
