### ISSUE TITLE
Rare rounding issue in polygon_to_array

### ISSUE THREAD

**Issue by mmann1123** [jgrss/geowombat#49]
I just ran into a case where generating the x and y coords doesn't match the original xarray dimensions. I can share the file if you want to see it. 

When running polygon_to_array:

`ds.shape `
6681 by 5172

after generating coordinates:
```
xcoords = np.arange(left + cellxh, left + cellxh + dst_width * abs(cellx), cellx)
ycoords = np.arange(top - cellyh, top - cellyh - dst_height * abs(celly), -celly)
len(xcoords)
6682
```

**Comment by mmann1123** [comment]
@jgrss yes that fixes it. Should it be merged?

**Comment by jgrss** [comment]
This has been merged, with the fix [here](https://github.com/jgrss/geowombat/commit/3908e92e68854d90395953ef31bb7a78d44fb7af).
