### ISSUE TITLE
The DataArray does not have a `crs` attribute.

### ISSUE THREAD

**Issue by VirginieBfd** [jgrss/geowombat#56]
Morning! 

First of all, thanks for the work, the library looks wicked!

I created a dedicated conda env by following your recommended steps:
```
pip install pip-tools
conda create -n geowombat python=3.7  cython scipy numpy zarr requests -c conda-forge
conda activate geowombat
sudo apt install libspatialindex-dev libgdal-dev
conda install -c conda-forge libspatialindex zarr requests
pip install git+https://github.com/jgrss/geowombat
python -c "import geowombat as gw;print(gw.__version__)"
```

Then I installed jupyterlab on top of the conda env to run the following:
![Screenshot from 2020-10-27 09-50-10](https://user-images.githubusercontent.com/26381053/97285291-ef2f7780-1839-11eb-85ff-3b19074227fe.png)

As you can see I am unable to save the raster despite I am using the example data available through the library. Same error message when trying to use some of my `tif` local files.

Any idea how to solve this bug? Thanks in advance!

**Comment by jgrss** [comment]
Hi, thanks for trying it!

The `gw` attribute is closed outside of the `with` context. Try it with:

```python
with gw.open('image.tif') as src:
    src.gw.to_raster()
```

or

```python
src = gw.open('image.tif')
src.gw.to_raster()
src.close()
```

**Comment by VirginieBfd** [comment]
My bad, that worked like a charm with your suggestions! If you're looking for contributors I might be interested in joining forces.

**Comment by jgrss** [comment]
@VirginieBfd Yes, we're happy to have more contributors. Let's get back in touch in a week or so after you've had a look at the library. (I am also online sporadically at the moment.)
