### ISSUE TITLE
mpool issue

### ISSUE THREAD

**Issue by mmann1123** [jgrss/geowombat#60]
Just wondering if you have any thoughts about this error with mpool. I tried making the chunks smaller, to no avail. After the stackerizer each chunk end up being (2152143, 42), which really isn't very large. Any tricks?

Also, would you prefer me ask these types of questions on git issue?

pt = ParallelTask(ds,
                        scheduler='mpool',
                        n_workers=2)
        print('n chunks %s' % pt.n_chunks)
        print('n windows %s' % pt.n_windows)
        res = pt.map(user_func, 6 )  

error                                     Traceback (most recent call last)
~/Documents/github/ET_drought_2019/scripts/crop_loss.py in
     146         print('n chunks %s' % pt.n_chunks)
     147         print('n windows %s' % pt.n_windows)
---> 148         res = pt.map(user_func, 6 )
     149

~/Documents/github/geowombat/geowombat/core/parallel.py in map(self, func, *args)
    144                     if self.scheduler == 'mpool':
    145
--> 146                         for result in tqdm(executor.imap_unordered(func, data_gen), total=n_windows_slice):
    147                             results.append(result)
    148

~/anaconda3/envs/geowombatdebug/lib/python3.7/site-packages/tqdm/std.py in __iter__(self)
   1163
   1164         try:
-> 1165             for obj in iterable:
   1166                 yield obj
   1167                 # Update and possibly print the progressbar.

~/anaconda3/envs/geowombatdebug/lib/python3.7/multiprocessing/pool.py in next(self, timeout)
    746         if success:
    747             return value
--> 748         raise value
    749
    750     __next__ = next                    # XXX

~/anaconda3/envs/geowombatdebug/lib/python3.7/multiprocessing/pool.py in _handle_tasks(taskqueue, put, outqueue, pool, cache)
    429                         break
    430                     try:
--> 431                         put(task)
    432                     except Exception as e:
    433                         job, idx = task[:2]

~/anaconda3/envs/geowombatdebug/lib/python3.7/multiprocessing/connection.py in send(self, obj)
    204         self._check_closed()
    205         self._check_writable()
--> 206         self._send_bytes(_ForkingPickler.dumps(obj))
    207
    208     def recv_bytes(self, maxlength=None):

~/anaconda3/envs/geowombatdebug/lib/python3.7/multiprocessing/connection.py in _send_bytes(self, buf)
    391         n = len(buf)
    392         # For wire compatibility with 3.2 and lower
--> 393         header = struct.pack("!i", n)
    394         if n > 16384:
    395             # The payload is large so Nagle's algorithm won't be triggered

error: 'i' format requires -2147483648 <= number <= 2147483647

**Comment by mmann1123** [comment]
from @jgrss  

I don't think the issue is with the individual workers, because as you say, the arrays are not that big. From what I read, the problem is with multiprocessing and it's memory management of queue workers. It seems that it might be more of an issue with Python <3.7. Which version are you running?

Possible short term solutions:

Pass keyword arguments to the pool executor so that you can try things like memory mapping or maxtasksperchild.

Try using concurrent.futures instead of multiprocessing by passing scheduler='processes'.

**Comment by jgrss** [comment]
@mmann1123 Can you show an example of what your input `ds` looks like so I can try and replicate it?

**Comment by jgrss** [comment]
How about something like this?

```python
from pathlib import Path
import dask.array as da
```

```python
class WriteDaskArray(object):

    def __init__(self,
                 filename,
                 overwrite=False,
                 **kwargs):

        self.filename = filename
        self.overwrite = overwrite
        self.kwargs = kwargs

        fpath = Path(self.filename)
        self.parent = fpath.parent
        self.stem = fpath.stem
        self.suffix = fpath.suffix

    def __setitem__(self, key, item):

        if len(key) == 3:

            index_range, y, x = key
            indexes = list(range(index_range.start + 1, index_range.stop + 1, index_range.step or 1))

        else:

            indexes = 1
            y, x = key

        out_filename = self.parent / f'{self.stem}_y{y.start:09d}_x{x.start:09d}_h{y.stop - y.start:09d}_w{x.stop - x.start:09d}{self.suffix}'
            
        if self.overwrite:

            if Path(out_filename).is_file():
                Path(out_filename).unlink()
                
        # TODO: write stuff here
        with open(out_filename, mode='w') as f:
            pass

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        pass
```

```python
with gw.open('image.tif') as src:
    
    # Transform data here
    data = ...

    with WriteDaskArray('out.file') as dst:

        res = da.store(da.squeeze(data.data),
                       dst,
                       lock=False,
                       compute=False)
        
        res.compute()
```

**Comment by mmann1123** [comment]
Thanks I will play with that, at the moment I am using parquet files b/c it allows multi-index which is helpful. Here's what I have. 

``` python
<xarray.DataArray (time: 7, band: 39, y: 5169, x: 6680)>
dask.array<concatenate, shape=(7, 39, 5169, 6680), dtype=float64, chunksize=(1, 38, 799, 799), chunktype=numpy.ndarray>
Coordinates:
  * time     (time) int64 2010 2011 2012 2013 2014 2015 2016
  * y        (y) float64 3.403 3.403 3.406 3.406 ... 9.202 9.204 9.207 9.209
  * x        (x) float64 33.0 33.0 33.0 33.0 33.01 ... 40.49 40.5 40.5 40.5 40.5
  * band     (band) object 1 2 3 4 5 6 7 8 9 ... 32 33 34 35 36 37 38 'r_code'
Attributes:
    transform:      (0.002245788210298804, 0.0, 32.99736617392033, 0.0, -0.00...
    crs:            +init=epsg:4326
    res:            (0.002245788210298804, 0.002245788210298804)
    is_tiled:       1
    nodatavals:     (nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, n...
    scales:         (1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1...
    offsets:        (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0...
    AREA_OR_POINT:  Area
    filename:       ['y000002586_x000000000_h000002586_w000003341.tif', 'y000...
    resampling:     nearest
```
I have been having some success with the following although with "threads". Not very efficient, but working. 
``` python


def user_func(*args):
 

    # Gather function arguments
    data, window_id, num_workers = list(itertools.chain(*args))    # num_workers=1

    # Send the computation to Dask
    X = Stackerizer(stack_dims = ('y','x','time'), direction='stack').fit_transform(data)   # NOTE stack y before x!!! 
    X.compute(scheduler='threads', num_workers=num_workers) 

    with open(out_folder+"/stacked_data_Xy_downcast_parts_window/log.txt", 'a') as the_file:
        the_file.write('working on %08d \t' % window_id)
        the_file.write( str(datetime.now()) +'\n')

    X = X.to_pandas() 
    X.columns = X.columns.astype(str)

    # # downcast to save memory 
    X = downcast_pandas(X)

    # save this approach wont write files in order 
    X.to_parquet(out_folder+'/stacked_data_Xy_downcast_parts_window/NDVI_2010-2016_Xy_croploss_'+ \
                                os.path.splitext(block)[0]+'_%05d.parquet' %  window_id)

```

**Comment by jgrss** [comment]
@mmann1123 Where is `Stackerizer` imported from?

**Comment by jgrss** [comment]
Nevermind, `from xr_fresh.transformers import Stackerizer` right?

**Comment by jgrss** [comment]
The following worked on a small array of random numbers. If it works on your large dataset, it might be good to add a more generic version of chunked writing with an optional user function for transforming data.

```python
def user_func(data):
    
    # The data from `da.store` are numpy arrays
    da = xr.DataArray(data=data,
             coords={'time': range(1, data.shape[0]+1),
                     'band': range(1, data.shape[1]+1),
                     'y': range(1, data.shape[2]+1),
                     'x': range(1, data.shape[3]+1)},
             dims=('time', 'band', 'y', 'x'))
    
    X = Stackerizer(stack_dims=('y','x','time'), 
                    direction='stack')\
            .fit_transform(da)

    X = X.to_pandas() 
    X.columns = X.columns.astype(str)    
    
    return X
```

```python
class WriteDaskArray(object):

    def __init__(self,
                 filename,
                 overwrite=False,
                 **kwargs):

        self.filename = filename
        self.overwrite = overwrite
        self.kwargs = kwargs

        fpath = Path(self.filename)
        self.parent = fpath.parent
        self.stem = fpath.stem
        self.suffix = fpath.suffix

    def __setitem__(self, key, item):

        if len(key) == 4:
            t, b, y, x = key
        elif len(key) == 3:
            b, y, x = key
        else:
            y, x = key

        out_filename = self.parent / f'{self.stem}_y{y.start:09d}_x{x.start:09d}_h{y.stop - y.start:09d}_w{x.stop - x.start:09d}{self.suffix}'
            
        if self.overwrite:

            if Path(out_filename).is_file():
                Path(out_filename).unlink()

        item = user_func(item)

        item.to_parquet(out_filename)

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        pass
```

```python
ntime = 7
nbands = 40
nrows = 100
ncols = 100

chunks = (7, 40, 50, 50)

src = xr.DataArray(data=da.random.random((ntime, nbands, nrows, ncols), chunks=chunks),
             coords={'time': range(1, ntime+1),
                     'band': range(1, nbands+1),
                     'y': range(1, nrows+1),
                     'x': range(1, ncols+1)},
             dims=('time', 'band', 'y', 'x'))

with WriteDaskArray('test.parquet') as dst:

    res = da.store(da.squeeze(src.data),
                   dst,
                   lock=False,
                   compute=False)

    res.compute()
```

**Comment by mmann1123** [comment]
Sorry how are you applying `user_func` here to create `da`?

**Comment by jgrss** [comment]
When `da.store` is called with a `dask.array` passed as the first argument, `WriteDaskArray` sends each chunk to a worker. In `__setitem__`, `item` is a numpy array. The numpy array is passed to the user function in `item = user_func(item)`, where it is converted to a `xarray.DataArray` and transformed.

**Comment by mmann1123** [comment]
Ok this is very interesting your WriteDaskArray is many orders of magnitude faster than the parallel task approach (1 sec per chunk vs 7 minutes.  I just figured out how to retain the coords and band names (I think, would appreciate you looking it over to make sure you don't see any stupid mistakes).  

``` python 

def user_func(data, src, t, b, y, x):

    # The data from `da.store` are numpy arrays

    da = xr.DataArray(
        data=data,
        coords={
            "time": src.time.values[t],
            "band": src.band.values[b],
            "y": src.y.values[y],
            "x": src.x.values[x],
        },
        dims=("time", "band", "y", "x"),
    )

    X = Stackerizer(stack_dims=("y", "x", "time"), direction="stack").fit_transform(da)

    X = X.to_pandas()
    X.columns = X.columns.astype(str)

    return X


class WriteDaskArray(object):
    def __init__(self, filename, src, overwrite=True):

        self.filename = filename
        self.overwrite = overwrite

        fpath = Path(self.filename)
        self.parent = fpath.parent
        self.stem = fpath.stem
        self.suffix = fpath.suffix

        self.src = src

    def __setitem__(self, key, item):

        if len(key) == 4:
            t, b, y, x = key
        elif len(key) == 3:
            b, y, x = key
        else:
            y, x = key

        out_filename = (
            self.parent
            / f"{self.stem}_y{y.start:09d}_x{x.start:09d}_h{y.stop - y.start:09d}_w{x.stop - x.start:09d}{self.suffix}"
        )

        if self.overwrite:

            if out_filename.is_file():
                out_filename.unlink()

        item = user_func(item, self.src, t, b, y, x)

        item.to_parquet(out_filename)

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        pass

 with gw.open(
        vrts, time_names=time_names, chunks=400
    ) as ds:   
 
        ds = ds.chunk({"time": -1, "band": -1, "y": "auto", "x": -1})  # rechunk to time
        print(ds)

# This could be used within a client context
with WriteDaskArray("/home/mmann1123/Desktop/test.parquet", ds) as dst:

    res = da.store(ds.data, dst, lock=False, compute=False)

    res.compute()
```

I also pass the xr array to WriteDaskArray which seems a bit sloppy, is there a better way to do this? 

``` python 
with WriteDaskArray("/home/mmann1123/Desktop/test.parquet", ds) as dst:
```
I think for my use case, it would be easier to label with a chunk_id similar to window_id from parallel task, do you think this is possible?

**Comment by mmann1123** [comment]
For the chunk id since I have it chunk by row, i guess I could just use the row number from y

**Comment by jgrss** [comment]
Hi @mmann1123 the code looks pretty good. The speedup isn't too surprising since it is using Dask to manage the task scheduling. The reason I have the other parallel option in geowombat is to provide an interface for large images. As long as the task overhead is manageable, Dask should be faster. 

Perhaps you could setup a simple dictionary for the chunk id. Something like:

```python
with WriteDaskArray("/home/mmann1123/Desktop/test.parquet", ds) as dst:
    dst.attrs['chunk_ids'] = dict(zip([f'{i:09d}-{j:09d}' for i in range(0, dst.gw.row_chunks) for j in range(0, dst.gw.col_chunks)], range(0, dst.gw.row_chunks*dst.gw.col_chunks)))
```

And then index `dst.chunk_ids` inside `WriteDaskArray` like `self.src.attrs[f'{y.start:09d}-{x.start:09d}']`.

**Comment by jgrss** [comment]
> I also pass the xr array to WriteDaskArray which seems a bit sloppy, is there a better way to do this?
I don't think so, other than passing the attributes you need individually. I would probably also pass the `Xarray.DataArray.gw`.

**Comment by mmann1123** [comment]
Ok thanks! Trying to get it working now.

**Comment by jgrss** [comment]
I just realized that the example above should have been:

```python
with gw.open(vrts, time_names=time_names, chunks=400) as ds:
    dst.attrs['chunk_ids'] = dict(zip([f'{i:09d}-{j:09d}' for i in range(0, dst.gw.row_chunks) for j in range(0, dst.gw.col_chunks)], range(0, dst.gw.row_chunks*dst.gw.col_chunks)))
```

**Comment by jgrss** [comment]
@mmann1123 I also remembered the `chunk_grid` property.

```python
with gw.open('...') as src:
    # df is a GeoDataFrame with unique ids for the chunks ('chunk' column)
    df = src.gw.chunk_grid
```

**Comment by jgrss** [comment]
@mmann1123 Did you use the dask solution? Can we close this issue?

**Comment by mmann1123** [comment]
resolved. Closing issue.
